### ISSUE TITLE
Notification will not dissappear

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CarlitoBriganteNT/android-notifier#172]
```
What steps will reproduce the problem?
1.Enabling the notification when the service is running
2.Starting the Service
3.Stopping the service

What is the expected output? What do you see instead?
When ticking the box that enables an ongoing notification to be shown on the 
phone when the service is running works at first but once I stop the service 
the notification remains, at all my attempts it won't go away until I reboot my 
phone

Please paste the application's log here (it should now be on your
clipboard):
D/WifiService(  124): ACTION_BATTERY_CHANGED pluggedType: 0
D/WifiService(  124): acquireWifiLockLocked: WifiLock{NetworkLocationProvider 
type=2 binder=android.os.Binder@45ef9f60}
D/WifiService(  124): ACTION_BATTERY_CHANGED pluggedType: 0
D/WifiService(  124): releaseWifiLockLocked: WifiLock{NetworkLocationProvider 
type=2 binder=android.os.Binder@45ef9f60}
D/WifiService(  124): ACTION_BATTERY_CHANGED pluggedType: 0
D/WifiWatchdogService(  124): (android.server.ServerThread) SKY18548 
(00:26:91:18:48:75) does not require the watchdog
D/WifiService(  124): ACTION_BATTERY_CHANGED pluggedType: 0
D/WifiService(  124): ACTION_BATTERY_CHANGED pluggedType: 0
D/WifiService(  124): ACTION_BATTERY_CHANGED pluggedType: 0
D/WifiService(  124): ACTION_SCREEN_OFF
D/WifiService(  124): setting ACTION_DEVICE_IDLE timer for 900000ms
D/WifiService(  124): ACTION_SCREEN_ON
V/WifiMonitor(  124): Event [CTRL-EVENT-TERMINATING - signal 15 received]
V/WifiStateTracker(  124): Connection to supplicant lost
D/WifiStateTracker(  124): Reset connections and stopping DHCP
D/WifiStateTracker(  124): Disabling interface
D/RemoteNotifier(10600): Using real bluetooth utils
D/RemoteNotifier(10600): Using level 5 caller ID
I/RemoteNotifier(10600): Starting notification service
D/RemoteNotifier(10600): Battery status: NOT charging
D/RemoteNotifier(10600): Got battery level: 28
D/RemoteNotifier(10600): Battery level change: 29
D/RemoteNotifier(10600): Notifying of battery state change
D/RemoteNotifier(10600): Sending notification: 
v2/d60a03d27b420b8e/8aecaa70ae0843/BATTERY/28/NOT charging, remaining charge: 
28%
D/RemoteNotifier(10600): Enabling bluetooth and delaying notification
D/BluetoothService(  124): Bluetooth state 10 -> 11
E/BluetoothEventLoop.cpp(  124): event_filter: Received signal 
org.freedesktop.DBus:NameAcquired from /org/freedesktop/DBus
D/BluetoothHidService.cpp(  124): hid_event_filter...
D/BluetoothService(  124): found 1 bonded devices
D/BluetoothService(  124): Bluetooth state 11 -> 12
D/BluetoothService(  124): updateDeviceServiceChannelCache(00:1A:7D:06:4C:60)
D/RemoteNotifier(10600): Method bluetooth connected, sending delayed 
notification after 5011ms
E/BluetoothService.cpp(  124): stopDiscoveryNative: D-Bus error in 
StopDiscovery: org.bluez.Error.Failed (Invalid discovery session)
E/AndroidRuntime(10600): FATAL EXCEPTION: Notification bluetooth for null
E/AndroidRuntime(10600): java.lang.NullPointerException
E/AndroidRuntime(10600):    at 
org.damazio.notifier.notification.BluetoothNotificationMethod.doSendNotification
(BluetoothNotificationMethod.java:154)
E/AndroidRuntime(10600):    at 
org.damazio.notifier.notification.BluetoothNotificationMethod.sendNotification(B
luetoothNotificationMethod.java:95)
E/AndroidRuntime(10600):    at 
org.damazio.notifier.notification.MethodEnablingNotifier.onTick(MethodEnablingNo
tifier.java:53)
E/AndroidRuntime(10600):    at 
android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:124)
E/AndroidRuntime(10600):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(10600):    at android.os.Looper.loop(Looper.java:123)
E/AndroidRuntime(10600):    at 
org.damazio.notifier.notification.Notifier.runNotificationThread(Notifier.java:7
5)
E/AndroidRuntime(10600):    at 
org.damazio.notifier.notification.Notifier.access$0(Notifier.java:65)
E/AndroidRuntime(10600):    at 
org.damazio.notifier.notification.Notifier$1.run(Notifier.java:54)
D/BluetoothService(  124): Registering hfag record
E/BluetoothEventLoop.cpp(  124): event_filter: Received signal 
org.bluez.Adapter:PropertyChanged from /org/bluez/10673/hci0
D/BluetoothService(  124): Registering hsag record
D/BluetoothService(  124): Registering opush record
E/BluetoothEventLoop.cpp(  124): event_filter: Received signal 
org.bluez.Adapter:PropertyChanged from /org/bluez/10673/hci0
D/BluetoothService(  124): Registering pbap record
D/RemoteNotifier(10707): Using real bluetooth utils
E/BluetoothService.cpp(  124): stopDiscoveryNative: D-Bus error in 
StopDiscovery: org.bluez.Error.Failed (Invalid discovery session)
D/RemoteNotifier(10707): Saving state
D/BluetoothService(  124): Bluetooth state 12 -> 13
V/BluetoothEventRedirector(10725): Received 
android.bluetooth.adapter.action.STATE_CHANGED
D/BluetoothService(  124): Bluetooth state 13 -> 10
V/BluetoothEventRedirector(10725): Received 
android.bluetooth.adapter.action.STATE_CHANGED
D/WifiService(  124): ACTION_BATTERY_CHANGED pluggedType: 0
D/WifiService(  124): acquireWifiLockLocked: WifiLock{NetworkLocationProvider 
type=2 binder=android.os.Binder@45ef9f60}
D/WifiService(  124): ACTION_BATTERY_CHANGED pluggedType: 0
V/WifiMonitor(  124): Event [CTRL-EVENT-STATE-CHANGE id=-1 state=2]
V/WifiStateTracker(  124): Connection to supplicant established, state=SCANNING
V/WifiStateTracker(  124): Changing supplicant state: SCANNING ==> SCANNING
D/RemoteNotifier(10754): Using real bluetooth utils
D/WifiService(  124): releaseWifiLockLocked: WifiLock{NetworkLocationProvider 
type=2 binder=android.os.Binder@45ef9f60}
V/WifiMonitor(  124): Event [Trying to associate with 00:26:91:18:48:75 
(SSID='SKY18548' freq=2412 MHz)]
V/WifiMonitor(  124): Event [CTRL-EVENT-STATE-CHANGE id=-1 state=3]
V/WifiStateTracker(  124): Changing supplicant state: SCANNING ==> ASSOCIATING
V/WifiMonitor(  124): Event [CTRL-EVENT-STATE-CHANGE id=1 state=4]
V/WifiStateTracker(  124): Changing supplicant state: ASSOCIATING ==> ASSOCIATED
V/WifiMonitor(  124): Event [Associated with 00:26:91:18:48:75]
V/WifiMonitor(  124): Event [CTRL-EVENT-STATE-CHANGE id=1 state=5]
V/WifiStateTracker(  124): Changing supplicant state: ASSOCIATED ==> 
FOUR_WAY_HANDSHAKE
V/WifiMonitor(  124): Event [CTRL-EVENT-STATE-CHANGE id=1 state=5]
V/WifiStateTracker(  124): Changing supplicant state: FOUR_WAY_HANDSHAKE ==> 
FOUR_WAY_HANDSHAKE
V/WifiMonitor(  124): Event [CTRL-EVENT-STATE-CHANGE id=1 state=6]
V/WifiStateTracker(  124): Changing supplicant state: FOUR_WAY_HANDSHAKE ==> 
GROUP_HANDSHAKE
V/WifiMonitor(  124): Event [CTRL-EVENT-STATE-CHANGE id=1 state=6]
V/WifiStateTracker(  124): Changing supplicant state: GROUP_HANDSHAKE ==> 
GROUP_HANDSHAKE
V/WifiMonitor(  124): Event [WPA: Key negotiation completed with 
00:26:91:18:48:75 [PTK=TKIP GTK=TKIP]]
V/WifiMonitor(  124): Event [CTRL-EVENT-STATE-CHANGE id=1 state=7]
V/WifiStateTracker(  124): Changing supplicant state: GROUP_HANDSHAKE ==> 
COMPLETED
V/WifiMonitor(  124): Event [CTRL-EVENT-CONNECTED - Connection to 
00:26:91:18:48:75 completed (auth) [id=1 id_str=]]
V/WifiStateTracker(  124): New network state is CONNECTED
D/WifiStateTracker(  124): DhcpHandler: DHCP request started
V/WifiStateTracker(  124): DhcpHandler: DHCP request succeeded
V/WifiStateTracker(  124): IP configuration: ipaddr 192.168.0.6 gateway 
192.168.0.1 netmask 255.255.255.0 dns1 192.168.0.1 dns2 0.0.0.0 DHCP server 
192.168.0.1 lease 86400 seconds
D/WifiWatchdogService(  124): (android.server.ServerThread) SKY18548 
(00:26:91:18:48:75) does not require the watchdog


What version of Android are you using?

```

Original issue reported on code.google.com by `did...@googlemail.com` on 23 Sep 2010 at 10:48

**Comment by GoogleCodeExporter** [comment]
```
Forgot to mention I'm running Android 2.2
```

Original comment by `did...@googlemail.com` on 23 Sep 2010 at 10:51
