### ISSUE TITLE
bluetooth error when client on windows loads

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CarlitoBriganteNT/android-notifier#190]
```
IMPORTANT: PLEASE search the existing issues (including closed ones) for
something similar before filing a new one.

What steps will reproduce the problem?
1.start program on windows
2.
3.

What is the expected output? What do you see instead?
btspp://localhost:7674047e6e474bf0831f209e3f9dd23f;name=AndroidNotifierService
2010-09-25 13:40:05,929 DEBUG [bluetooth] - socket
2010-09-25 13:40:05,929 DEBUG [bluetooth] - socket[836] opened
2010-09-25 13:40:05,929 DEBUG [bluetooth] - socket[836] bind
2010-09-25 13:40:05,929 DEBUG [bluetooth] - socket[836] listen
2010-09-25 13:40:05,929 DEBUG [bluetooth] - socket[836] getsockchannel
2010-09-25 13:40:05,929 DEBUG [bluetooth] - service channel  1
2010-09-25 13:40:05,945 DEBUG [bluetooth] - registerService
2010-09-25 13:40:05,960 DEBUG [bluetooth] - will throw exception 
javax/bluetooth/ServiceRegistrationException(Failed to register service; 
[10022] An invalid argument was supplied.)
2010-09-25 13:40:05,960 DEBUG [bluetooth] - socket[836] close
2010-09-25 13:40:06,038 ERROR [BluetoothNotificationReceiver] - Error setting 
up bluetooth
javax.bluetooth.ServiceRegistrationException: Failed to register service; 
[10022] An invalid argument was supplied.
    at com.intel.bluetooth.BluetoothStackMicrosoft.registerService(Native Method)
    at com.intel.bluetooth.BluetoothStackMicrosoft.rfServerOpen(BluetoothStackMicrosoft.java:748)
    at com.intel.bluetooth.BluetoothRFCommConnectionNotifier.<init>(BluetoothRFCommConnectionNotifier.java:42)
    at com.intel.bluetooth.MicroeditionConnector.openImpl(MicroeditionConnector.java:377)
    at com.intel.bluetooth.MicroeditionConnector.open(MicroeditionConnector.java:162)
    at javax.microedition.io.Connector.open(Connector.java:83)
    at com.google.code.notifier.desktop.notification.bluetooth.BluetoothNotificationReceiver$1.run(BluetoothNotificationReceiver.java:69)
    at java.lang.Thread.run(Unknown Source)

What version of the product are you using? On what operating system?


if  i uncheck and recheck bluetooth as an option in the program then it will 
work
```

Original issue reported on code.google.com by `ddarv...@gmail.com` on 29 Sep 2010 at 4:34

**Comment by GoogleCodeExporter** [comment]
Original comment by `rdamazio@gmail.com` on 29 Sep 2010 at 5:31
- Added labels: **Component-Communication**, **OpSys-Windows**

**Comment by GoogleCodeExporter** [comment]
```
Did you pair your device with your PC before running the desktop client like 
BluetoothHowto says?
```

Original comment by `lehph...@gmail.com` on 29 Sep 2010 at 7:59

**Comment by GoogleCodeExporter** [comment]
```
yes. i did pair it properly. like i said above once i uncheck and recheck the 
bluetooth box in the desktop client then the notifications work.
```

Original comment by `ddarv...@gmail.com` on 29 Sep 2010 at 10:17

**Comment by GoogleCodeExporter** [comment]
```
Does it happen everytime you run AND?

Bluetooth error messages usually don't tell much, we'll need to try different 
things until one works. Could you please copy this jar file to where you 
installed AND and then run "java -jar android-notifier-desktop-0.4.jar" in 
command line? What is the output of it?

http://dl.dropbox.com/u/1401233/android-notifier-desktop-0.4.jar
```

Original comment by `lehph...@gmail.com` on 30 Sep 2010 at 8:17

**Comment by GoogleCodeExporter** [comment]
```
Taking over lehphyro's issues.
```

Original comment by `rdamazio@gmail.com` on 11 Jan 2011 at 4:31
