### ISSUE TITLE
force close on different occasions

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CarlitoBriganteNT/android-notifier#193]
```
What steps will reproduce the problem?
1.
2.
3.

What is the expected output? What do you see instead?


Please paste the application's log here (it should now be on your
clipboard):
D/WifiService(   92): ACTION_SCREEN_ON
D/WifiService(   92): enable and start wifi due to updateWifiState
D/WifiService(   92): ACTION_SCREEN_OFF
D/WifiService(   92): ACTION_BATTERY_CHANGED pluggedType: 1
D/WifiService(   92): ACTION_BATTERY_CHANGED pluggedType: 1
D/WifiService(   92): ACTION_BATTERY_CHANGED pluggedType: 1
D/WifiService(   92): ACTION_BATTERY_CHANGED pluggedType: 1
D/WifiService(   92): ACTION_BATTERY_CHANGED pluggedType: 1
D/WifiService(   92): ACTION_BATTERY_CHANGED pluggedType: 1
D/WifiService(   92): ACTION_BATTERY_CHANGED pluggedType: 1
D/WifiService(   92): ACTION_BATTERY_CHANGED pluggedType: 1
D/WifiService(   92): ACTION_BATTERY_CHANGED pluggedType: 1
D/WifiService(   92): ACTION_SCREEN_ON
D/WifiService(   92): enable and start wifi due to updateWifiState
D/WifiService(   92): ACTION_BATTERY_CHANGED pluggedType: 1
D/WifiService(   92): ACTION_SCREEN_OFF
D/WifiService(   92): ACTION_SCREEN_ON
D/WifiService(   92): enable and start wifi due to updateWifiState
D/WifiService(   92): ACTION_SCREEN_OFF
D/WifiService(   92): ACTION_SCREEN_ON
D/WifiService(   92): enable and start wifi due to updateWifiState
D/WifiService(   92): ACTION_SCREEN_OFF
D/WifiService(   92): ACTION_BATTERY_CHANGED pluggedType: 1
D/WifiService(   92): ACTION_SCREEN_ON
D/WifiService(   92): enable and start wifi due to updateWifiState
E/AndroidRuntime( 9810): FATAL EXCEPTION: main
E/AndroidRuntime( 9810): java.lang.RuntimeException: Unable to start receiver 
org.damazio.notifier.locale.FireReceiver: java.lang.NullPointerException: 
Argument must not be null
E/AndroidRuntime( 9810):    at 
android.app.ActivityThread.handleReceiver(ActivityThread.java:2957)
E/AndroidRuntime( 9810):    at 
android.app.ActivityThread.access$3200(ActivityThread.java:135)
E/AndroidRuntime( 9810):    at 
android.app.ActivityThread$H.handleMessage(ActivityThread.java:2198)
E/AndroidRuntime( 9810):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 9810):    at android.os.Looper.loop(Looper.java:144)
E/AndroidRuntime( 9810):    at 
android.app.ActivityThread.main(ActivityThread.java:4937)
E/AndroidRuntime( 9810):    at java.lang.reflect.Method.invokeNative(Native 
Method)
E/AndroidRuntime( 9810):    at java.lang.reflect.Method.invoke(Method.java:521)
E/AndroidRuntime( 9810):    at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
E/AndroidRuntime( 9810):    at 
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
E/AndroidRuntime( 9810):    at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 9810): Caused by: java.lang.NullPointerException: Argument 
must not be null
E/AndroidRuntime( 9810):    at java.lang.Enum.valueOf(Enum.java:171)
E/AndroidRuntime( 9810):    at 
org.damazio.notifier.locale.LocaleSettings$OnOffKeep.valueOf(LocaleSettings.java
:1)
E/AndroidRuntime( 9810):    at 
org.damazio.notifier.locale.FireReceiver.getOnOffKeep(FireReceiver.java:64)
E/AndroidRuntime( 9810):    at 
org.damazio.notifier.locale.FireReceiver.onReceive(FireReceiver.java:56)
E/AndroidRuntime( 9810):    at 
android.app.ActivityThread.handleReceiver(ActivityThread.java:2941)
E/AndroidRuntime( 9810):    ... 10 more
D/WifiService(   92): ACTION_BATTERY_CHANGED pluggedType: 1
D/WifiWatchdogService(   92): (android.server.ServerThread) asdf 
(00:1b:11:8f:57:7e) does not require the watchdog
D/RemoteNotifier(10033): Locale starting service
I/RemoteNotifier(10033): Starting notification service
D/RemoteNotifier(10033): Using real bluetooth utils
D/RemoteNotifier(10033): Battery status: Full
D/RemoteNotifier(10033): Got battery level: 99
D/RemoteNotifier(10033): Battery level change: 100
D/RemoteNotifier(10033): Notifying of battery state change
D/RemoteNotifier(10033): Not starting service again
D/RemoteNotifier(10033): Sending notification: 
v2/200141cf2cb1499a/870a63a02eeb57/BATTERY/99/Full, remaining charge: 99%
D/RemoteNotifier(10033): Sending wifi notification to IP 255.255.255.255
D/RemoteNotifier(10033): Sending over UDP
D/RemoteNotifier(10033): Sent over UDP
I/RemoteNotifier(10033): Sent notification over WiFi.
D/RemoteNotifier(10033): Not starting service again
D/RemoteNotifier(10033): Not starting service again
D/RemoteNotifier(10033): Sending notification: 
v2/200141cf2cb1499a/45b29db4f0f0f/PING//Test notification
E/RemoteNotifier(10033): Not sending bluetooth notification - not enabled
E/RemoteNotifier(10033): Not sending bluetooth notification - not enabled
D/RemoteNotifier(10033): Restoring state
D/WifiService(   92): setWifiEnabled( mAirplaneModeOverwridden=)false
D/WifiStateTracker(   92): Reset connections and stopping DHCP
D/WifiStateTracker(   92): Disabling interface
I/WifiHW  (   92): wifi_stop_supplicant enter
V/WifiMonitor(   92): Event [CTRL-EVENT-TERMINATING - signal 15 received]
V/WifiStateTracker(   92): Connection to supplicant lost
I/WifiHW  (   92): wifi_stop_supplicant end right 2
I/WifiHW  (   92): wifi_unload_driver enter
I/WifiHW  (   92): wifi_unload_driver end right 2
D/RemoteNotifier(10033): Locale stopping service
D/AndroidRuntime(10033): Shutting down VM
E/AndroidRuntime(10033): FATAL EXCEPTION: main
E/AndroidRuntime(10033): java.lang.RuntimeException: Unable to start receiver 
org.damazio.notifier.locale.FireReceiver: java.lang.NullPointerException: 
Argument must not be null
E/AndroidRuntime(10033):    at 
android.app.ActivityThread.handleReceiver(ActivityThread.java:2957)
E/AndroidRuntime(10033):    at 
android.app.ActivityThread.access$3200(ActivityThread.java:135)
E/AndroidRuntime(10033):    at 
android.app.ActivityThread$H.handleMessage(ActivityThread.java:2198)
E/AndroidRuntime(10033):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(10033):    at android.os.Looper.loop(Looper.java:144)
E/AndroidRuntime(10033):    at 
android.app.ActivityThread.main(ActivityThread.java:4937)
E/AndroidRuntime(10033):    at java.lang.reflect.Method.invokeNative(Native 
Method)
E/AndroidRuntime(10033):    at java.lang.reflect.Method.invoke(Method.java:521)
E/AndroidRuntime(10033):    at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
E/AndroidRuntime(10033):    at 
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
E/AndroidRuntime(10033):    at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(10033): Caused by: java.lang.NullPointerException: Argument 
must not be null
E/AndroidRuntime(10033):    at java.lang.Enum.valueOf(Enum.java:171)
E/AndroidRuntime(10033):    at 
org.damazio.notifier.locale.LocaleSettings$OnOffKeep.valueOf(LocaleSettings.java
:1)
E/AndroidRuntime(10033):    at 
org.damazio.notifier.locale.FireReceiver.getOnOffKeep(FireReceiver.java:64)
E/AndroidRuntime(10033):    at 
org.damazio.notifier.locale.FireReceiver.onReceive(FireReceiver.java:56)
E/AndroidRuntime(10033):    at 
android.app.ActivityThread.handleReceiver(ActivityThread.java:2941)
E/AndroidRuntime(10033):    ... 10 more
D/RemoteNotifier(10156): Using real bluetooth utils


What version of Android are you using?

```

Original issue reported on code.google.com by `peter.v...@gmail.com` on 30 Sep 2010 at 12:38

**Comment by GoogleCodeExporter** [comment]
```
Force close happens from tasker when I try to edit a profile. Will investigate 
more just wanted to paste the stacktrace here
```

Original comment by `peter.v...@gmail.com` on 30 Sep 2010 at 12:39

**Comment by GoogleCodeExporter** [comment]
```
ok it happens when I edit the existing rule in tasker. If I remove and add it 
again it works and can be. Maybe something changed in the AN, I compiled it 
from svn instad using the one from the market.
```

Original comment by `peter.v...@gmail.com` on 30 Sep 2010 at 12:55

**Comment by GoogleCodeExporter** [comment]
```
Funny, I fixed this one literally 10 seconds before seeing your issue :) you're 
running from head right?
Please hold a few mins for a few + other additions.
```

Original comment by `rdamazio@gmail.com` on 30 Sep 2010 at 12:55
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
if by head you mean trunk then yes :)
```

Original comment by `peter.v...@gmail.com` on 30 Sep 2010 at 12:56

**Comment by GoogleCodeExporter** [comment]
```
Yes, trunk - I work with too many different version control systems every day 
(svn, hg, git and perforce), sorry :)
```

Original comment by `rdamazio@gmail.com` on 30 Sep 2010 at 1:06

**Comment by GoogleCodeExporter** [comment]
```
I thought so, no problem. but svn ist still at rev 346 so I still must wait 
until the changes come through
```

Original comment by `peter.v...@gmail.com` on 30 Sep 2010 at 1:21

**Comment by GoogleCodeExporter** [comment]
```
Submitted fix in r348.
```

Original comment by `rdamazio@gmail.com` on 30 Sep 2010 at 1:30

**Comment by GoogleCodeExporter** [comment]
```
got it. works like a charm now.
```

Original comment by `peter.v...@gmail.com` on 30 Sep 2010 at 1:43
