### ISSUE TITLE
Ping & Battery Notifcations: OK   Everything else:  Error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CarlitoBriganteNT/android-notifier#198]
```
IMPORTANT: PLEASE search the existing issues (including closed ones) for
something similar before filing a new one.

What steps will reproduce the problem?
1.  missed calls on my phone create notification error message on desktop
2.
3.

What is the expected output? What do you see instead?
I would expect to get a desktop notification of missed calls and texts to my 
phone.  Instead I see on my desktop "an error occurred while receiving wifi 
notification".  Pings and battery charge notifications work as expected.


What version of the product are you using? On what operating system?
Phone is Droid 2.   Desktop is Windows XP.

Please provide any additional information below.
Log:
2010-09-30 22:01:15,312 INFO [ApplicationImpl] - Starting SWT
2010-09-30 22:01:19,500 INFO [ApplicationImpl] - Showing tray icon
2010-09-30 22:01:19,859 DEBUG [ServiceServerImpl] - Starting service server on 
port [10700]
2010-09-30 22:01:19,953 DEBUG [InetAddresses] - Looking for local address
2010-09-30 22:01:20,312 INFO [ApplicationImpl] - Starting [System default] 
broadcaster
2010-09-30 22:01:20,312 INFO [ApplicationImpl] - Starting [TCP] receiver
2010-09-30 22:01:22,171 INFO [ApplicationImpl] - Starting [UDP] receiver
2010-09-30 22:01:22,765 INFO [ApplicationImpl] - Removing from startup
2010-09-30 22:01:32,609 DEBUG [InetAddresses] - Local address found
2010-09-30 22:01:34,140 INFO [Main] - There can be only one instance of Android 
Notifier Desktop running at a time
2010-09-30 22:02:06,015 INFO [ApplicationImpl] - Adding to startup
2010-09-30 22:02:23,265 INFO [ApplicationImpl] - Starting [bluetooth] receiver
2010-09-30 22:02:23,421 DEBUG [bluetooth] - Java 1.4+ detected: 1.6.0_21; Java 
HotSpot(TM) Client VM; Sun Microsystems Inc.
2010-09-30 22:02:23,453 DEBUG [bluetooth] - Use stack ClassLoader
2010-09-30 22:02:23,453 DEBUG [bluetooth] - set dll dir 
C:\DOCUME~1\Ramey\LOCALS~1\Temp\bluecove_Ramey_0
2010-09-30 22:02:25,031 DEBUG [bluetooth] - Library loaded from 
C:\DOCUME~1\Ramey\LOCALS~1\Temp\bluecove_Ramey_0\intelbth.dll
2010-09-30 22:02:25,031 DEBUG [bluetooth] - nativeDebugCallback ON
2010-09-30 22:02:25,062 DEBUG [bluetooth] - socket error [10047] An address 
incompatible with the requested protocol was used.
2010-09-30 22:02:25,125 DEBUG [bluetooth] - BluetoothStack detected 0
2010-09-30 22:02:25,125 ERROR [bluetooth] - BluetoothStack not detected
2010-09-30 22:02:25,140 ERROR [ApplicationImpl] - Error starting [bluetooth] 
receiver
java.lang.IllegalStateException: Bluetooth not detected, disabling it.
    at com.google.code.notifier.desktop.notification.bluetooth.BluetoothNotificationReceiver.doStart(BluetoothNotificationReceiver.java:55)
    at com.google.code.notifier.desktop.app.AbstractLifecycle.start(AbstractLifecycle.java:36)
    at com.google.code.notifier.desktop.app.ApplicationImpl.startLifecycle(ApplicationImpl.java:249)
    at com.google.code.notifier.desktop.app.ApplicationImpl.adjustLifecycle(ApplicationImpl.java:303)
    at com.google.code.notifier.desktop.app.ApplicationImpl.adjustBluetoothReceiver(ApplicationImpl.java:136)
    at com.google.code.notifier.desktop.view.PreferencesDialog$4$1.run(PreferencesDialog.java:225)
    at java.lang.Thread.run(Unknown Source)
Caused by: javax.bluetooth.BluetoothStateException: BluetoothStack not detected
    at com.intel.bluetooth.BlueCoveImpl.detectStack(BlueCoveImpl.java:496)
    at com.intel.bluetooth.BlueCoveImpl.access$500(BlueCoveImpl.java:69)
    at com.intel.bluetooth.BlueCoveImpl$1.run(BlueCoveImpl.java:1044)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.intel.bluetooth.BlueCoveImpl.detectStackPrivileged(BlueCoveImpl.java:1042)
    at com.intel.bluetooth.BlueCoveImpl.getBluetoothStack(BlueCoveImpl.java:1035)
    at javax.bluetooth.LocalDevice.getLocalDeviceInstance(LocalDevice.java:75)
    at javax.bluetooth.LocalDevice.getLocalDevice(LocalDevice.java:95)
    at com.google.code.notifier.desktop.notification.bluetooth.BluetoothNotificationReceiver.doStart(BluetoothNotificationReceiver.java:51)
    ... 6 more
2010-09-30 22:05:01,875 INFO [NotificationManagerImpl] - Notification received: 
notificationId=437abbe22848d, type=Ping
2010-09-30 22:05:02,531 ERROR [NotificationChannelHandler] - Error handling 
network notification
java.io.IOException: An existing connection was forcibly closed by the remote 
host
    at sun.nio.ch.SocketDispatcher.read0(Native Method)
    at sun.nio.ch.SocketDispatcher.read(Unknown Source)
    at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
    at sun.nio.ch.IOUtil.read(Unknown Source)
    at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
    at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:322)
    at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:281)
    at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:201)
    at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
2010-09-30 22:05:20,656 INFO [NotificationManagerImpl] - Notification received: 
notificationId=437abc14b8b11, type=Ping
2010-09-30 22:05:29,312 INFO [NotificationManagerImpl] - Notification received: 
notificationId=437abc1ca78e1, type=Ping
2010-09-30 22:05:37,921 INFO [NotificationManagerImpl] - Notification received: 
notificationId=82be1e96f154e8, type=Battery
2010-09-30 22:05:40,609 INFO [NotificationManagerImpl] - Notification received: 
notificationId=437abc2654a9f, type=Ping
2010-09-30 22:05:48,796 INFO [NotificationManagerImpl] - Notification received: 
notificationId=437abc2e813b6, type=Ping
2010-09-30 23:15:18,734 INFO [NotificationManagerImpl] - Notification received: 
notificationId=82be3bf01fdac5, type=Battery
2010-09-30 23:15:22,468 INFO [NotificationManagerImpl] - Notification received: 
notificationId=437acb1ebc433, type=Ping
2010-09-30 23:16:37,375 INFO [NotificationManagerImpl] - Notification received: 
notificationId=437acb6360c45, type=Ping
2010-09-30 23:17:06,734 INFO [NotificationManagerImpl] - Notification received: 
notificationId=82be3cb02a2011, type=Battery
2010-09-30 23:21:39,484 INFO [NotificationManagerImpl] - Notification received: 
notificationId=437acc78458b4, type=Ping
2010-09-30 23:22:34,031 INFO [NotificationManagerImpl] - Notification received: 
notificationId=82be3ef52a0533, type=Battery
2010-09-30 23:24:05,062 INFO [NotificationManagerImpl] - Notification received: 
notificationId=437accfdb436c, type=Ping
2010-09-30 23:26:09,468 INFO [NotificationManagerImpl] - Notification received: 
notificationId=437acd6fb8f25, type=Ping
2010-09-30 23:29:42,703 INFO [NotificationManagerImpl] - Notification received: 
notificationId=437ace33293e6, type=Ping
2010-09-30 23:40:03,093 INFO [NotificationManagerImpl] - Notification received: 
notificationId=437ad06bbeb95, type=Ping
2010-09-30 23:45:21,046 INFO [NotificationManagerImpl] - Notification received: 
notificationId=82be4870da0ee3, type=Battery
2010-09-30 23:46:51,375 INFO [NotificationManagerImpl] - Notification received: 
notificationId=437ad1e1f3d4a, type=Ping
2010-09-30 23:46:58,687 INFO [NotificationManagerImpl] - Notification received: 
notificationId=437ad1e8a5f54, type=Ping
2010-09-30 23:50:56,140 INFO [NotificationManagerImpl] - Notification received: 
notificationId=82be4a6891a87e, type=Battery
2010-10-01 12:32:38,593 INFO [Main] - There can be only one instance of Android 
Notifier Desktop running at a time
2010-10-01 12:34:08,531 INFO [Main] - There can be only one instance of Android 
Notifier Desktop running at a time
2010-10-01 12:45:56,531 INFO [NotificationManagerImpl] - Notification received: 
notificationId=437b7938f8b68, type=Ping
2010-10-01 12:46:48,968 INFO [NotificationManagerImpl] - Notification received: 
notificationId=82bf8d4193fc73, type=Battery
2010-10-01 12:46:59,640 ERROR [NotificationChannelHandler] - Error handling 
network notification
java.io.IOException: An existing connection was forcibly closed by the remote 
host
    at sun.nio.ch.SocketDispatcher.read0(Native Method)
    at sun.nio.ch.SocketDispatcher.read(Unknown Source)
    at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
    at sun.nio.ch.IOUtil.read(Unknown Source)
    at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
    at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:322)
    at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:281)
    at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:201)
    at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
2010-10-01 12:48:42,531 INFO [NotificationManagerImpl] - Notification received: 
notificationId=437b79c77dddc, type=Ping
2010-10-01 12:49:42,875 ERROR [NotificationChannelHandler] - Error handling 
network notification
java.io.IOException: An existing connection was forcibly closed by the remote 
host
    at sun.nio.ch.SocketDispatcher.read0(Native Method)
    at sun.nio.ch.SocketDispatcher.read(Unknown Source)
    at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
    at sun.nio.ch.IOUtil.read(Unknown Source)
    at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
    at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:322)
    at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:281)
    at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:201)
    at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
2010-10-01 14:18:11,546 INFO [NotificationManagerImpl] - Notification received: 
notificationId=437b8d0caa86b, type=Ping

```

Original issue reported on code.google.com by `rmillet...@gmail.com` on 1 Oct 2010 at 6:24

**Comment by GoogleCodeExporter** [comment]
Original comment by `rdamazio@gmail.com` on 1 Oct 2010 at 6:34
- Added labels: **Component-Communication**, **OpSys-Windows**, **Stability**

**Comment by GoogleCodeExporter** [comment]
```
There is really nothing I can do about it, the OS is reporting the android app 
is closing the connection abruptly. I would suggest calling 
socket.shutdownOutput() after flush() and before close() in 
IpNotificationMethod to see if it helps.
```

Original comment by `lehph...@gmail.com` on 1 Oct 2010 at 6:52

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the quick reponse.   Suggestion is way over my head, not a coder and 
have no idea how to execute that idea, but thanks anyway!.   Will uninstall and 
try again at some later date.
```

Original comment by `rmillet...@gmail.com` on 1 Oct 2010 at 7:28

**Comment by GoogleCodeExporter** [comment]
```
Sorry, my suggestion is for rdamazio actually. You'll see this happen sometimes 
only, I got it only once.
```

Original comment by `lehph...@gmail.com` on 1 Oct 2010 at 7:41

**Comment by GoogleCodeExporter** [comment]
```
I get the following using 0.5.1 on Win7 which I guess is the same issue, pings 
work but messages produce this error :

2010-10-08 21:42:36,143 INFO [NotificationManagerImpl] - Notification received: 
notificationId=38288218171819376, type=Battery
2010-10-08 21:42:37,138 DEBUG [bluetooth] - connection accepted
2010-10-08 21:42:37,138 DEBUG [bluetooth] - socket[1788] getpeeraddress
2010-10-08 21:42:37,138 DEBUG [bluetooth] - connection open, open now 1
2010-10-08 21:42:37,139 DEBUG [bluetooth] - socket[1788] recv 
(byte[],int,int=4096)
2010-10-08 21:42:37,182 DEBUG [bluetooth] - Connection closed
2010-10-08 21:42:37,182 ERROR [BluetoothNotificationReceiver] - Error handling 
bluetooth notification
com.notifier.desktop.exception.ParseException: 
com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol 
message, the input ended unexpectedly in the middle of a field.  This could 
mean either than the input has been truncated or that an embedded message 
misreported its own length.
    at com.notifier.desktop.parsing.MultiNotificationParser.parse(MultiNotificationParser.java:53)
    at com.notifier.desktop.parsing.MultiNotificationParser.parse(MultiNotificationParser.java:27)
    at com.notifier.desktop.notification.bluetooth.BluetoothNotificationReceiver$1.run(BluetoothNotificationReceiver.java:87)
    at java.lang.Thread.run(Unknown Source)
Caused by: com.google.protobuf.InvalidProtocolBufferException: While parsing a 
protocol message, the input ended unexpectedly in the middle of a field.  This 
could mean either than the input has been truncated or that an embedded message 
misreported its own length.
    at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:49)
    at com.google.protobuf.CodedInputStream.refillBuffer(CodedInputStream.java:691)
    at com.google.protobuf.CodedInputStream.readRawByte(CodedInputStream.java:714)
    at com.google.protobuf.CodedInputStream.readRawVarint32(CodedInputStream.java:318)
    at com.notifier.desktop.parsing.MultiNotificationParser.parse(MultiNotificationParser.java:42)
    ... 3 more
2010-10-08 21:42:37,183 DEBUG [bluetooth] - closing RFCOMM Connection 1788
2010-10-08 21:42:37,183 DEBUG [bluetooth] - connection closed, open now 0
2010-10-08 21:42:37,183 DEBUG [bluetooth] - socket[1788] close



```

Original comment by `SmnTh...@gmail.com` on 9 Oct 2010 at 8:32

**Comment by GoogleCodeExporter** [comment]
```
@SmnThorn This message has been posted in issue 217. In short, some 
notifications are not sent properly over bluetoot. Issue 3 is about bluetooth 
errors you might want to star that one to get updates about it.
```

Original comment by `lehph...@gmail.com` on 9 Oct 2010 at 2:24

**Comment by GoogleCodeExporter** [comment]
```
Hello
please send me source code or give source code link .please 
```

Original comment by `ghorivip...@gmail.com` on 19 Aug 2014 at 4:13
