### ISSUE TITLE
Bluetooth notification fails on Win 7

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CarlitoBriganteNT/android-notifier#201]
```
IMPORTANT: PLEASE search the existing issues (including closed ones) for
something similar before filing a new one.

What steps will reproduce the problem?
1. install and start the Android notifier on Win 7 Professional 32bit
2. Pair the phone and the laptop
3. Send a test ping from the phone

What is the expected output? What do you see instead?

I expect a pop-up from the taskbar, as I get from the wifi notification. (I 
send that simultaneously, to check that the notifier is partially working). 
Instead, I get a Windows error dialog with the caption "Android Notifier 
Bluetooth Error" and the message "An error ocurred [sic] while receiving 
bluetooth notification"

What version of the product are you using? On what operating system?

I am using the Notifier Desktop 0.4.0, on Windows 7 Professional, 32 bit 
(running on a Lenovo x200s which has a built-in bluetooth adaptor) 


Please provide any additional information below.

I don't have a spare bluetooth adapter to test it on my desktop, but the phone 
otherwise communicates fine with the laptop over bluetooth

```

Original issue reported on code.google.com by `seatr...@gmail.com` on 4 Oct 2010 at 4:25
- Merged into: #39

**Comment by GoogleCodeExporter** [comment]
```
Leandro, please check whether this is a duplicate of issue 3.
```

Original comment by `rdamazio@gmail.com` on 4 Oct 2010 at 4:39

**Comment by GoogleCodeExporter** [comment]
```
I don't think it is a bug where no bluetooth gets sent. I am using an HTC hero 
(droid eris in the states, I think) and not a Nexus. 

I have just found the error log, which looks like this (repeated for multiple 
failures)

2010-10-04 17:18:43,114 INFO [NotificationManagerImpl] - Notification received: 
notificationId=490c6594d3862, type=Ping
2010-10-04 17:18:46,124 DEBUG [bluetooth] - connection accepted
2010-10-04 17:18:46,125 DEBUG [bluetooth] - socket[1020] getpeeraddress
2010-10-04 17:18:46,125 DEBUG [bluetooth] - connection open, open now 1
2010-10-04 17:18:46,125 DEBUG [bluetooth] - socket[1020] recv 
(byte[],int,int=8192)
2010-10-04 17:18:46,370 DEBUG [bluetooth] - Connection closed
2010-10-04 17:18:46,370 ERROR [BluetoothNotificationReceiver] - Error handling 
bluetooth notification
java.lang.IllegalStateException: Protocol version [] is not supported
    at com.google.code.notifier.desktop.parsing.StringNotificationParser.parse(StringNotificationParser.java:36)
    at com.google.code.notifier.desktop.parsing.StringNotificationParser.parse(StringNotificationParser.java:25)
    at com.google.code.notifier.desktop.notification.bluetooth.BluetoothNotificationReceiver$1.run(BluetoothNotificationReceiver.java:80)
    at java.lang.Thread.run(Unknown Source)
2010-10-04 17:18:46,371 DEBUG [bluetooth] - closing RFCOMM Connection 1020
2010-10-04 17:18:46,371 DEBUG [bluetooth] - connection closed, open now 0
2010-10-04 17:18:46,372 DEBUG [bluetooth] - socket[1020] close
2010-10-04 17:18:46,372 DEBUG [bluetooth] - socket[1120] accept


```

Original comment by `seatr...@gmail.com` on 4 Oct 2010 at 4:44

**Comment by GoogleCodeExporter** [comment]
```
Isn't that a duplicate of issue 39 then?
```

Original comment by `rdamazio@gmail.com` on 4 Oct 2010 at 4:48

**Comment by GoogleCodeExporter** [comment]
```
Yes it is.
```

Original comment by `lehph...@gmail.com` on 4 Oct 2010 at 5:07
- Changed state: **Duplicate**
