### ISSUE TITLE
Sending message to a Handler on a dead thread

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CarlitoBriganteNT/android-notifier#206]
```
Got it when receiving a sms message (running apk built from trunk):

W/MessageQueue(13069): Handler{44928af0} sending message to a Handler on a dead 
thread
W/MessageQueue(13069): java.lang.RuntimeException: Handler{44928af0} sending 
message to a Handler on a dead thread
W/MessageQueue(13069): at 
android.os.MessageQueue.enqueueMessage(MessageQueue.java:179)
W/MessageQueue(13069): at android.os.Handler.sendMessageAtTime(Handler.java:457)
W/MessageQueue(13069): at 
android.os.Handler.sendMessageDelayed(Handler.java:430)
W/MessageQueue(13069): at 
android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:133)
W/MessageQueue(13069): at android.os.Handler.dispatchMessage(Handler.java:99)
W/MessageQueue(13069): at android.os.Looper.loop(Looper.java:123)
W/MessageQueue(13069): at 
org.damazio.notifier.notification.Notifier.runNotificationThread(Notifier.java:1
74)
W/MessageQueue(13069): at 
org.damazio.notifier.notification.Notifier.access$0(Notifier.java:165)
W/MessageQueue(13069): at 
org.damazio.notifier.notification.Notifier$1.run(Notifier.java:91)
```

Original issue reported on code.google.com by `lehph...@gmail.com` on 5 Oct 2010 at 3:19

**Comment by GoogleCodeExporter** [comment]
Original comment by `rdamazio@gmail.com` on 5 Oct 2010 at 4:43
- Added labels: **Component-Communication**, **Priority-High**, **Stability**
- Removed labels: **Priority-Low**

**Comment by GoogleCodeExporter** [comment]
```
Connect my phone network
```

Original comment by `Torentsis@gmail.com` on 21 Oct 2012 at 1:52
