### ISSUE TITLE
crash when message received

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CarlitoBriganteNT/android-notifier#208]
```
What steps will reproduce the problem?
1. Sending a test message.

What is the expected output? What do you see instead?
And error occurred while receiving **** message. For Bluetooth and WiFi 
connections.

Please paste the application's log here (it should now be on your
clipboard):D/WifiService(   98): releaseWifiLockLocked: 
WifiLock{NetworkLocationProvider type=2 binder=android.os.Binder@4616aab0}
D/WifiService(   98): enable and start wifi due to updateWifiState
D/WifiWatchdogService(   98): (android.server.ServerThread) csuguest 
(28:93:fe:4f:ca:e0) does not require the watchdog
D/WifiService(   98): acquireWifiLockLocked: WifiLock{NetworkLocationProvider 
type=2 binder=android.os.Binder@4616aab0}
D/WifiService(   98): enable and start wifi due to updateWifiState
D/WifiService(   98): releaseWifiLockLocked: WifiLock{NetworkLocationProvider 
type=2 binder=android.os.Binder@4616aab0}
D/WifiService(   98): enable and start wifi due to updateWifiState
D/WifiService(   98): acquireWifiLockLocked: WifiLock{NetworkLocationProvider 
type=2 binder=android.os.Binder@4616aab0}
D/WifiService(   98): enable and start wifi due to updateWifiState
D/WifiService(   98): releaseWifiLockLocked: WifiLock{NetworkLocationProvider 
type=2 binder=android.os.Binder@4616aab0}
D/WifiService(   98): enable and start wifi due to updateWifiState
D/WifiWatchdogService(   98): (android.server.ServerThread) csuguest 
(28:93:fe:d2:4d:b0) does not require the watchdog
D/WifiService(   98): acquireWifiLockLocked: WifiLock{NetworkLocationProvider 
type=2 binder=android.os.Binder@4616aab0}
D/WifiService(   98): enable and start wifi due to updateWifiState
D/WifiService(   98): releaseWifiLockLocked: WifiLock{NetworkLocationProvider 
type=2 binder=android.os.Binder@4616aab0}
D/WifiService(   98): enable and start wifi due to updateWifiState
D/WifiService(   98): acquireWifiLockLocked: WifiLock{NetworkLocationProvider 
type=2 binder=android.os.Binder@4616aab0}
D/WifiService(   98): enable and start wifi due to updateWifiState
D/WifiService(   98): releaseWifiLockLocked: WifiLock{NetworkLocationProvider 
type=2 binder=android.os.Binder@4616aab0}
D/WifiService(   98): enable and start wifi due to updateWifiState
D/WifiService(   98): acquireWifiLockLocked: WifiLock{NetworkLocationProvider 
type=2 binder=android.os.Binder@4616aab0}
D/WifiService(   98): enable and start wifi due to updateWifiState
D/WifiService(   98): releaseWifiLockLocked: WifiLock{NetworkLocationProvider 
type=2 binder=android.os.Binder@4616aab0}
D/WifiService(   98): enable and start wifi due to updateWifiState
D/WifiService(   98): acquireWifiLockLocked: WifiLock{MAIL_WIFI_LOCK type=1 
binder=android.os.BinderProxy@46549308}
D/WifiService(   98): enable and start wifi due to updateWifiState
D/WifiService(   98): acquireWifiLockLocked: WifiLock{MAIL_WIFI_LOCK type=1 
binder=android.os.BinderProxy@465f35c8}
D/WifiService(   98): enable and start wifi due to updateWifiState
D/WifiService(   98): acquireWifiLockLocked: WifiLock{MAIL_WIFI_LOCK type=1 
binder=android.os.BinderProxy@46548cd0}
D/WifiService(   98): enable and start wifi due to updateWifiState
D/WifiService(   98): releaseWifiLockLocked: WifiLock{MAIL_WIFI_LOCK type=1 
binder=android.os.BinderProxy@46548cd0}
D/WifiService(   98): enable and start wifi due to updateWifiState
D/WifiService(   98): releaseWifiLockLocked: WifiLock{MAIL_WIFI_LOCK type=1 
binder=android.os.BinderProxy@46549308}
D/WifiService(   98): enable and start wifi due to updateWifiState
D/WifiService(   98): releaseWifiLockLocked: WifiLock{MAIL_WIFI_LOCK type=1 
binder=android.os.BinderProxy@465f35c8}
D/WifiService(   98): enable and start wifi due to updateWifiState
D/WifiWatchdogService(   98): (android.server.ServerThread) csuguest 
(28:93:fe:4f:c7:d0) does not require the watchdog
D/WifiWatchdogService(   98): (android.server.ServerThread) csuguest 
(00:0c:85:2e:ff:d4) does not require the watchdog
D/WifiWatchdogService(   98): (android.server.ServerThread) csuguest 
(00:0c:85:0c:70:66) does not require the watchdog
D/WifiWatchdogService(   98): (android.server.ServerThread) csuguest 
(00:0c:85:14:5b:23) does not require the watchdog
D/WifiWatchdogService(   98): (android.server.ServerThread) csuguest 
(00:0c:85:04:ee:37) does not require the watchdog
D/WifiWatchdogService(   98): (android.server.ServerThread) csuguest 
(00:0c:85:14:5b:23) does not require the watchdog
D/WifiWatchdogService(   98): (android.server.ServerThread) csuguest 
(00:1a:a2:da:b2:71) does not require the watchdog
D/WifiWatchdogService(   98): (android.server.ServerThread) csuguest 
(00:1a:a2:da:b1:d1) does not require the watchdog
D/WifiWatchdogService(   98): (android.server.ServerThread) csuguest 
(00:07:0e:b9:56:de) does not require the watchdog
D/WifiWatchdogService(   98): (android.server.ServerThread) csuguest 
(00:07:0e:b9:58:3d) does not require the watchdog
D/WifiWatchdogService(   98): (android.server.ServerThread) csuguest 
(00:0c:30:f1:44:b1) does not require the watchdog
D/WifiService(   98): ACTION_BATTERY_CHANGED pluggedType: 0
D/WifiService(   98): ACTION_BATTERY_CHANGED pluggedType: 0
D/WifiService(   98): ACTION_BATTERY_CHANGED pluggedType: 2
D/WifiService(   98): ACTION_SCREEN_ON
D/WifiService(   98): enable and start wifi due to updateWifiState
D/WifiService(   98): ACTION_SCREEN_OFF
D/WifiService(   98): ACTION_SCREEN_ON
D/WifiService(   98): enable and start wifi due to updateWifiState
D/WifiService(   98): acquireWifiLockLocked: WifiLock{NetworkLocationProvider 
type=2 binder=android.os.Binder@4616aab0}
D/WifiService(   98): enable and start wifi due to updateWifiState
D/WifiService(   98): releaseWifiLockLocked: WifiLock{NetworkLocationProvider 
type=2 binder=android.os.Binder@4616aab0}
D/WifiService(   98): enable and start wifi due to updateWifiState
D/WifiService(   98): releaseWifiLockLocked: WifiLock{fring type=1 
binder=android.os.BinderProxy@4649f190}
D/WifiService(   98): enable and start wifi due to updateWifiState
D/WifiService(   98): acquireWifiLockLocked: WifiLock{fring type=1 
binder=android.os.BinderProxy@46201f30}
D/WifiService(   98): enable and start wifi due to updateWifiState
D/WifiService(   98): acquireWifiLockLocked: WifiLock{NetworkLocationProvider 
type=2 binder=android.os.Binder@4616aab0}
D/WifiService(   98): enable and start wifi due to updateWifiState
D/WifiService(   98): releaseWifiLockLocked: WifiLock{NetworkLocationProvider 
type=2 binder=android.os.Binder@4616aab0}
D/WifiService(   98): enable and start wifi due to updateWifiState
D/WifiService(   98): acquireWifiLockLocked: WifiLock{NetworkLocationProvider 
type=2 binder=android.os.Binder@4616aab0}
D/WifiService(   98): enable and start wifi due to updateWifiState
D/WifiService(   98): releaseWifiLockLocked: WifiLock{NetworkLocationProvider 
type=2 binder=android.os.Binder@4616aab0}
D/WifiService(   98): enable and start wifi due to updateWifiState
D/WifiService(   98): ACTION_BATTERY_CHANGED pluggedType: 2
D/RemoteNotifier(25255): Sent notification over Bluetooth (0 retries).
E/BluetoothEventLoop.cpp(   98): event_filter: Received signal 
org.bluez.Device:PropertyChanged from 
/org/bluez/25400/hci0/dev_00_26_08_BF_4A_0F
V/BluetoothEventRedirector(25365): Received android.bleutooth.device.action.UUID
D/BluetoothService(   98): Release wake lock for discoverable mode
D/RemoteNotifier(25255): Sending notification: 
v2/22a100000d9de156/48ce516ff54a0/PING//Test notification
D/RemoteNotifier(25255): Sending wifi notification to IP 255.255.255.255
D/RemoteNotifier(25255): Sending over UDP
D/RemoteNotifier(25255): Sent over UDP
I/RemoteNotifier(25255): Sent notification over WiFi.
E/BluetoothService.cpp(   98): stopDiscoveryNative: D-Bus error in 
StopDiscovery: org.bluez.Error.Failed (Invalid discovery session)
E/BluetoothEventLoop.cpp(   98): event_filter: Received signal 
org.bluez.Adapter:PropertyChanged from /org/bluez/25400/hci0
E/BluetoothService.cpp(   98): stopDiscoveryNative: D-Bus error in 
StopDiscovery: org.bluez.Error.Failed (Invalid discovery session)
D/RemoteNotifier(25255): Connecting to Bluetooth device ERIC-PC
D/BluetoothService(   98): updateDeviceServiceChannelCache(00:26:08:BF:4A:0F)
D/BluetoothService(   98):  uuid(application): 
7674047e-6e47-4bf0-831f-209e3f9dd23f 1
D/BluetoothService(   98): Making callback for 
7674047e-6e47-4bf0-831f-209e3f9dd23f with result 1
V/BluetoothEventRedirector(25365): Received android.bleutooth.device.action.UUID
E/BluetoothEventLoop.cpp(   98): event_filter: Received signal 
org.bluez.Device:PropertyChanged from 
/org/bluez/25400/hci0/dev_00_26_08_BF_4A_0F
D/RemoteNotifier(25255): Sending notification: 
v2/22a100000d9de156/48ce51733232d/PING//Test notification
E/BluetoothService.cpp(   98): stopDiscoveryNative: D-Bus error in 
StopDiscovery: org.bluez.Error.Failed (Invalid discovery session)
E/BluetoothEventLoop.cpp(   98): event_filter: Received signal 
org.bluez.Device:PropertyChanged from 
/org/bluez/25400/hci0/dev_00_26_08_BF_4A_0F
D/RemoteNotifier(25255): Sending wifi notification to IP 255.255.255.255
D/RemoteNotifier(25255): Sending over UDP
D/RemoteNotifier(25255): Sent over UDP
I/RemoteNotifier(25255): Sent notification over WiFi.
D/RemoteNotifier(25255): Sent notification over Bluetooth (0 retries).
E/BluetoothService.cpp(   98): stopDiscoveryNative: D-Bus error in 
StopDiscovery: org.bluez.Error.Failed (Invalid discovery session)
D/BluetoothService(   98): updateDeviceServiceChannelCache(00:26:08:BF:4A:0F)
D/RemoteNotifier(25255): Connecting to Bluetooth device ERIC-PC
E/BluetoothEventLoop.cpp(   98): event_filter: Received signal 
org.bluez.Device:PropertyChanged from 
/org/bluez/25400/hci0/dev_00_26_08_BF_4A_0F
D/BluetoothService(   98): updateDeviceServiceChannelCache(00:26:08:BF:4A:0F)
D/BluetoothService(   98):  uuid(application): 
7674047e-6e47-4bf0-831f-209e3f9dd23f 1
D/BluetoothService(   98): Making callback for 
7674047e-6e47-4bf0-831f-209e3f9dd23f with result 1
D/RemoteNotifier(25255): Sent notification over Bluetooth (0 retries).
V/BluetoothEventRedirector(25365): Received android.bleutooth.device.action.UUID
V/BluetoothEventRedirector(25365): Received android.bleutooth.device.action.UUID
V/BluetoothEventRedirector(25365): Received android.bleutooth.device.action.UUID
E/BluetoothEventLoop.cpp(   98): event_filter: Received signal 
org.bluez.Device:PropertyChanged from 
/org/bluez/25400/hci0/dev_00_26_08_BF_4A_0F
V/BluetoothEventRedirector(25365): Received android.bleutooth.device.action.UUID
E/BluetoothEventLoop.cpp(   98): event_filter: Received signal 
org.bluez.Device:PropertyChanged from 
/org/bluez/25400/hci0/dev_00_26_08_BF_4A_0F
E/BluetoothEventLoop.cpp(   98): event_filter: Received signal 
org.bluez.Device:PropertyChanged from 
/org/bluez/25400/hci0/dev_00_26_08_BF_4A_0F
E/BluetoothEventLoop.cpp(   98): event_filter: Received signal 
org.bluez.Device:PropertyChanged from 
/org/bluez/25400/hci0/dev_00_26_08_BF_4A_0F
E/BluetoothEventLoop.cpp(   98): event_filter: Received signal 
org.bluez.Device:PropertyChanged from 
/org/bluez/25400/hci0/dev_00_26_08_BF_4A_0F
D/RemoteNotifier(25255): Sending notification: 
v2/22a100000d9de156/48ce51ae040e1/PING//Test notification
D/RemoteNotifier(25255): Sending wifi notification to IP 255.255.255.255
D/RemoteNotifier(25255): Sending over UDP
D/RemoteNotifier(25255): Sent over UDP
I/RemoteNotifier(25255): Sent notification over WiFi.
E/BluetoothService.cpp(   98): stopDiscoveryNative: D-Bus error in 
StopDiscovery: org.bluez.Error.Failed (Invalid discovery session)
E/BluetoothService.cpp(   98): stopDiscoveryNative: D-Bus error in 
StopDiscovery: org.bluez.Error.Failed (Invalid discovery session)
D/RemoteNotifier(25255): Connecting to Bluetooth device ERIC-PC
D/BluetoothService(   98): updateDeviceServiceChannelCache(00:26:08:BF:4A:0F)
D/BluetoothService(   98):  uuid(application): 
7674047e-6e47-4bf0-831f-209e3f9dd23f 1
D/BluetoothService(   98): Making callback for 
7674047e-6e47-4bf0-831f-209e3f9dd23f with result 1
V/BluetoothEventRedirector(25365): Received android.bleutooth.device.action.UUID
E/BluetoothEventLoop.cpp(   98): event_filter: Received signal 
org.bluez.Device:PropertyChanged from 
/org/bluez/25400/hci0/dev_00_26_08_BF_4A_0F
E/BluetoothEventLoop.cpp(   98): event_filter: Received signal 
org.bluez.Device:PropertyChanged from 
/org/bluez/25400/hci0/dev_00_26_08_BF_4A_0F
D/BluetoothService(   98): updateDeviceServiceChannelCache(00:26:08:BF:4A:0F)
D/RemoteNotifier(25255): Sent notification over Bluetooth (0 retries).
V/BluetoothEventRedirector(25365): Received android.bleutooth.device.action.UUID
E/BluetoothEventLoop.cpp(   98): event_filter: Received signal 
org.bluez.Device:PropertyChanged from 
/org/bluez/25400/hci0/dev_00_26_08_BF_4A_0F
V/BluetoothEventRedirector(25365): Received android.bleutooth.device.action.UUID



What version of Android are you using? Froyo 

```

Original issue reported on code.google.com by `eric.nei...@gmail.com` on 5 Oct 2010 at 10:50
- Merged into: #3

**Comment by GoogleCodeExporter** [comment]
```
I'm confused - you pasted a log from the android application, but only the 
desktop application receives messages, which one is causing problems? Also, if 
it's the desktop, which desktop application are you using?

Thanks
```

Original comment by `rdamazio@gmail.com` on 5 Oct 2010 at 10:51
- Changed state: **Waiting**

**Comment by GoogleCodeExporter** [comment]
```
I am receiving the same error (An error occurred while receiving bluetooth 
notification.). I receive this error every time I try to do a test 
notification. I haven't tried the wifi notifications because it doesn't fit my 
usage. I am running the MultiDroidNotifier-0.5.1-x86_64.dmg version on this 
year's model 15" Macbook Pro running OS X 10.6.4.

I am using an HTC Evo running Android 2.2 (DamageControl Rom) and using version 
0.2.8 of the phone client.

The error I receive in the PC log is as follows:

2010-10-06 18:56:59,625 INFO [ApplicationImpl] - Starting SWT
2010-10-06 18:57:00,222 INFO [ApplicationImpl] - Showing tray icon
2010-10-06 18:57:00,298 DEBUG [ServiceServerImpl] - Starting service server on 
port [10700]
2010-10-06 18:57:00,397 DEBUG [InetAddresses] - Looking for local address
2010-10-06 18:57:00,536 DEBUG [InetAddresses] - Local address found
2010-10-06 18:57:00,611 INFO [ApplicationImpl] - Starting [System default] 
broadcaster
2010-10-06 18:57:00,611 INFO [ApplicationImpl] - Starting [bluetooth] receiver
2010-10-06 18:57:00,943 DEBUG [bluetooth] - Java 1.4+ detected: 1.6.0_20; Java 
HotSpot(TM) 64-Bit Server VM; Apple Inc.
2010-10-06 18:57:01,112 DEBUG [bluetooth] - Use stack ClassLoader
2010-10-06 18:57:01,145 DEBUG [bluetooth] - set dll dir 
/var/folders/ed/ed9igiD3E0WLsmH03RDGBE+++TQ/-Tmp-/bluecove_cna21_0
2010-10-06 18:57:01,211 DEBUG [bluetooth] - Library loaded from 
/var/folders/ed/ed9igiD3E0WLsmH03RDGBE+++TQ/-Tmp-/bluecove_cna21_0/libbluecove.j
nilib
2010-10-06 18:57:01,212 DEBUG [bluetooth] - BluetoothStack selected mac
2010-10-06 18:57:01,213 DEBUG [bluetooth] - nativeDebugCallback ON
2010-10-06 18:57:01,213 DEBUG [bluetooth] - 
getLocalDeviceSupportedSoftwareVersion
2010-10-06 18:57:01,224 DEBUG [bluetooth] - localDeviceSupportedSoftwareVersion 
20000
2010-10-06 18:57:01,226 DEBUG [bluetooth] - isLocalDeviceFeatureParkMode
2010-10-06 18:57:01,229 DEBUG [bluetooth] - getLocalDeviceBluetoothAddress
2010-10-06 18:57:01,238 INFO [ApplicationImpl] - Removing from startup
2010-10-06 18:57:01,239 DEBUG [bluetooth] - open using BlueCove 
javax.microedition.io.Connector
2010-10-06 18:57:01,239 DEBUG [bluetooth] - connecting 
btspp://localhost:7674047e6e474bf0831f209e3f9dd23f;name=AndroidNotifierService;a
uthenticate=true
2010-10-06 18:57:01,248 DEBUG [bluetooth] - isLocalDevicePowerOn
2010-10-06 18:57:01,262 DEBUG [bluetooth] - RFCOMM server created, ChannelID 4
2010-10-06 18:57:01,266 DEBUG [bluetooth] - create ChannelController to accept 
incoming connection
2010-10-06 18:57:03,267 DEBUG [bluetooth] - will throw exception 
javax/bluetooth/BluetoothConnectionException(Failed to open connection(2) 
[0xe00002cd])
2010-10-06 18:57:03,373 ERROR [BluetoothNotificationReceiver] - Error handling 
bluetooth notification
javax.bluetooth.BluetoothConnectionException: Failed to open connection(2) 
[0xe00002cd]
    at com.intel.bluetooth.BluetoothStackOSX.rfServerAcceptAndOpenRfServerConnection(Native Method)
    at com.intel.bluetooth.BluetoothRFCommConnectionNotifier.acceptAndOpen(BluetoothRFCommConnectionNotifier.java:74)
    at com.notifier.desktop.notification.bluetooth.BluetoothNotificationReceiver$1.run(BluetoothNotificationReceiver.java:83)
    at java.lang.Thread.run(Thread.java:637)
2010-10-06 18:57:03,386 DEBUG [bluetooth] - create ChannelController to accept 
incoming connection


```

Original comment by `emeka.an...@gmail.com` on 6 Oct 2010 at 11:00

**Comment by GoogleCodeExporter** [comment]
```
I think this issue is duplicate of issue 3. We should merge them to have only 
one place to discuss bluetooth issues. A lot of HTC devices have bluetooth 
issues.
```

Original comment by `lehph...@gmail.com` on 6 Oct 2010 at 11:54
- Changed state: **Duplicate**
- Added labels: **Component-Communication**, **OpSys-Android**, **OpSys-Desktop**, **Priority-Medium**, **Type-Defect**

**Comment by GoogleCodeExporter** [comment]
```
Issue 296 has been merged into this issue.
```

Original comment by `rdamazio@gmail.com` on 24 Nov 2010 at 10:50
