### ISSUE TITLE
Wi-Fi Error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CarlitoBriganteNT/android-notifier#209]
```
What steps will reproduce the problem?
1. Connect phone to same local network as computer.
2. Install desktop and phone clients, with each running.
3. Send test message with only LAN scanning on in desktop client.

What is the expected output? What do you see instead?
Error dialog box with the following: "An error occurred while receiving wifi 
notification: For input string: "cd6cf19374fe3ec7""

What version of the product are you using? On what operating system?
Desktop v0.5.0
Android v0.2.8

Please provide any additional information below.
Error occurs consistently with same input string referenced with using global 
broadcasting, DHCP, or specified client IP. Error dialog appears for each test 
message sent, instantaneously.
```

Original issue reported on code.google.com by `cameron1...@gmail.com` on 6 Oct 2010 at 2:51

**Comment by GoogleCodeExporter** [comment]
```
Leandro, can you look at this one? Appears to be client-side at first, but 
could be some communication issue.

Thanks
```

Original comment by `rdamazio@gmail.com` on 6 Oct 2010 at 5:23

**Comment by GoogleCodeExporter** [comment]
```
Please, attach your log file here.
```

Original comment by `lehph...@gmail.com` on 6 Oct 2010 at 1:27

**Comment by GoogleCodeExporter** [comment]
```
2010-10-06 16:56:25,456 ERROR [NotificationChannelHandler] - Error handling 
network notification
java.lang.NumberFormatException: For input string: "c3db939307a75d26"
    at java.lang.NumberFormatException.forInputString(Unknown Source)
    at java.lang.Long.parseLong(Unknown Source)
    at com.notifier.desktop.parsing.TextNotificationParser.parse(TextNotificationParser.java:65)
    at com.notifier.desktop.parsing.MultiNotificationParser.parse(MultiNotificationParser.java:51)
    at com.notifier.desktop.parsing.MultiNotificationParser.parse(MultiNotificationParser.java:27)
    at com.notifier.desktop.notification.wifi.NotificationDecoder.decode(NotificationDecoder.java:42)
    at org.jboss.netty.handler.codec.oneone.OneToOneDecoder.handleUpstream(OneToOneDecoder.java:72)
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:274)
    at org.jboss.netty.channel.socket.oio.OioDatagramWorker.run(OioDatagramWorker.java:84)
    at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
```

Original comment by `persson....@gmail.com` on 6 Oct 2010 at 2:57

**Comment by GoogleCodeExporter** [comment]
```
Happens the same with me in Windows Seven x64
```

Original comment by `l.vit...@gmail.com` on 6 Oct 2010 at 3:30

**Comment by GoogleCodeExporter** [comment]
```
Ok, fixed in trunk (r411), I think this is critical, we have to release version 
0.5.1 with this fix ASAP.
```

Original comment by `lehph...@gmail.com` on 6 Oct 2010 at 3:38
- Changed state: **Fixed**
- Added labels: **Component-Logic**, **OpSys-Desktop**, **Priority-Critical**, **Usability**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
```
Issue 211 has been merged into this issue.
```

Original comment by `lehph...@gmail.com` on 6 Oct 2010 at 3:38

**Comment by GoogleCodeExporter** [comment]
```
Perfectly fixed mine; sorry I forgot to include the log initially!
```

Original comment by `cameron1...@gmail.com` on 6 Oct 2010 at 6:39

**Comment by GoogleCodeExporter** [comment]
```
Issue 232 has been merged into this issue.
```

Original comment by `lehph...@gmail.com` on 13 Oct 2010 at 2:14
