### ISSUE TITLE
Cant get MultiDroidNotifier-0.5.1-x86 to install.  UI error running, thinking installed on 64 bit system.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CarlitoBriganteNT/android-notifier#212]
```
IMPORTANT: PLEASE search the existing issues (including closed ones) for
something similar before filing a new one.

What steps will reproduce the problem?
1. Attempt to install 32 bit system, caused error.
2. Attempt to install 64 bit system, caused expected error.
3. Remove all installs and attempt 32 bit install again.

What is the expected output? What do you see instead?
Error message is:
Could not load UI. Make sure you are using the correct version (32 or 64 bit) 
for your system.  Both Operatijng System and Java have to be 64 bit if you want 
to run the 64 bit version of this program.

What version of the product are you using? On what operating system?
Using Windows XP Pro SP3

Please provide any additional information below.

```

Original issue reported on code.google.com by `jimmyj...@gmail.com` on 6 Oct 2010 at 5:39

**Comment by GoogleCodeExporter** [comment]
```
You can see which version of java you have running java -version in terminal.
```

Original comment by `lehph...@gmail.com` on 6 Oct 2010 at 5:58

**Comment by GoogleCodeExporter** [comment]
```
Checking my computer, I have 1.6.0_21.  I also tried 5.0 and it did install, 
but bt issues.
```

Original comment by `jimmyj...@gmail.com` on 6 Oct 2010 at 6:04

**Comment by GoogleCodeExporter** [comment]
```
It doesn't run on java 5, you need java 6. What is the output of java -version?
```

Original comment by `lehph...@gmail.com` on 6 Oct 2010 at 6:21

**Comment by GoogleCodeExporter** [comment]
```
For me the same problem.
Windows 7 32Bit; Java 1.6.0_21
```

Original comment by `dirk.hop...@gmail.com` on 6 Oct 2010 at 6:37

**Comment by GoogleCodeExporter** [comment]
```
I tried MultiDroidNotifier-0.5-x86.exe instead of 
MultiDroidNotifier-0.5.1-x86.exe and 0.5.0 installed, but I had bt issues.  I 
can run different versions of Java.  I can run release 18, 17 and 16 of Version 
1.6
```

Original comment by `jimmyj...@gmail.com` on 6 Oct 2010 at 6:43

**Comment by GoogleCodeExporter** [comment]
```
This doesnt work for me either, jsut tried installing for the first time,

Installed MultiDroidNotifier-0.5.1-x86.exe on Windows XP SP3 with Java 6.

My Java -version output:

java version "1.6.0_21"
Java(TM) SE Runtime Environment (build 1.6.0_21-b07)
Java HotSpot(TM) Client VM (build 17.0-b17, mixed mode, sharing)
```

Original comment by `MTGcts...@gmail.com` on 6 Oct 2010 at 6:49

**Comment by GoogleCodeExporter** [comment]
```
This seems to be the relevant log entry...

2010-10-06 20:58:39,058 INFO [ApplicationImpl] - Starting SWT
2010-10-06 20:58:39,379 INFO [ApplicationImpl] - Showing tray icon
2010-10-06 20:58:39,757 ERROR [ApplicationImpl] - Error showing tray icon
java.lang.ClassFormatError: Extra bytes at the end of class file 
com/notifier/desktop/tray/SwtTrayManager$5
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(Unknown Source)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.access$000(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at com.notifier.desktop.tray.SwtTrayManager.start(SwtTrayManager.java:111)
    at com.notifier.desktop.app.ApplicationImpl.start(ApplicationImpl.java:79)
    at com.notifier.desktop.Main.main(Main.java:106)
```

Original comment by `SmnTh...@gmail.com` on 6 Oct 2010 at 7:14

**Comment by GoogleCodeExporter** [comment]
```
Ok, I've uploaded the wrong file for 32-bit Windows, uploaded a new one now, 
please download it again.
```

Original comment by `lehph...@gmail.com` on 6 Oct 2010 at 7:16
- Added labels: **OpSys-Windows**

**Comment by GoogleCodeExporter** [comment]
```
You probably will have to clear your browser cache or use another browser, 
Firefox in my machine thinks the new file is the same as the previous one and 
doesn't download it.
```

Original comment by `lehph...@gmail.com` on 6 Oct 2010 at 7:20

**Comment by GoogleCodeExporter** [comment]
```
I'm afraid no change for me - still the same error in the log file.
```

Original comment by `SmnTh...@gmail.com` on 6 Oct 2010 at 7:27

**Comment by GoogleCodeExporter** [comment]
```
@SmnThorn This error has never been reported before, you have a corrupt file, 
try to install it in another hard drive or check your disk for errors using 
some disk utility. Make sure you have Sun Java 6 or OpenJDK 6 installed too, I 
did not test it with other JVMs.
```

Original comment by `lehph...@gmail.com` on 6 Oct 2010 at 7:35

**Comment by GoogleCodeExporter** [comment]
```
Thanks - can confirm it was the cache issue (new file upload works).
```

Original comment by `SmnTh...@gmail.com` on 6 Oct 2010 at 7:40

**Comment by GoogleCodeExporter** [comment]
```
Works for me now. Thanks.
```

Original comment by `MTGcts...@gmail.com` on 6 Oct 2010 at 8:37

**Comment by GoogleCodeExporter** [comment]
```
32 bit windows & java. (java version "1.6.0_21")
I did download the erroneous version yesterday, but I have since tried to 
clearing my cache and using another browser, but I still get this error when 
the program runs.
```

Original comment by `squir...@gmail.com` on 7 Oct 2010 at 10:05

**Comment by GoogleCodeExporter** [comment]
```
@squiredd Try again or download the 64-bit version just in case you happen to 
have Java 64-bit installed, this error no longer happens in my Windows XP 
32-bit machine. I'm letting this issue open so people looking only on open 
issues will find it, but this is fixed.
```

Original comment by `lehph...@gmail.com` on 7 Oct 2010 at 11:00
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Still no joy. Version 5.0 installs and runs, but only logs errors when a BT 
message arrives. Version 5.1 can not run due to the version warning (32 or 64 
bit).

I am certain I am running 32 bit Vista Professional, and fairly certain you can 
not install 64 bit Java on 32 bit windows. My Java version is the latest as 
previously posted. I am also as certain as I can be that this is not a browser 
cache issue (also already posted above).

Oh well, I will check back next version. Thanks for the help.
```

Original comment by `squir...@gmail.com` on 8 Oct 2010 at 2:43

**Comment by GoogleCodeExporter** [comment]
```
@squiredd This is the same installer served from dropbox: 
http://dl.dropbox.com/u/1401233/MultiDroidNotifier-0.5.1-x86.exe

If you attach your log file here, I can see what the error you get is about.
```

Original comment by `lehph...@gmail.com` on 8 Oct 2010 at 3:13

**Comment by GoogleCodeExporter** [comment]
```
That actually works, thank a lot.

What I have done so far: 
1.completely uninstalled AND
2.completely uninstalled Growl for windows

3.Installed the link you specified.
4.Works.
5.Installed Snarl/Paw (on co-workers advice). Still works.

In hindsight, I should have uninstall-ed Growl and tried that before now. 
Either some proxy/cache was preventing me from downloading the correct file, or 
the lingering Growl app was somehow interfering with the execution of AND.

Cheers.

```

Original comment by `squir...@gmail.com` on 8 Oct 2010 at 7:45

**Comment by GoogleCodeExporter** [comment]
```
I use Growl for Windows here and have not experienced issues running both, I 
think your log file would help us know what happened exactly but that's not 
necessary anymore, I'm glad it's working for you now :)
```

Original comment by `lehph...@gmail.com` on 8 Oct 2010 at 7:54
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
I am getting this issue too. I opened a new defect (297) but then I located 
this one in a search. Currently running Windows 7 64x and Java 1.6.0_16. I am 
pretty sure I'm using 32x Java however which shouldn't matter (only if I was on 
a 32x machine trying to use 64x Java... correct?).

What I've done so far...

1. Removed all version of Java
2. Downloaded and reinstalled latest Java VM from Sun.
3. Removed Notifier software using Revo, cleaned registry and removed directory 
left-overs.
4. Installed MultiDroidNotifier-0.5.1-x86 into a fresh directory.

Still received error message.
```

Original comment by `rugger...@gmail.com` on 25 Nov 2010 at 12:11
