### ISSUE TITLE
Error Message reported from Mac

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CarlitoBriganteNT/android-notifier#227]
```
IMPORTANT: PLEASE search the existing issues (including closed ones) for
something similar before filing a new one.

What steps will reproduce the problem?
1. Pairing the device
2. Recieving any notifaction
3.

What is the expected output? What do you see instead?
Reciept of notifications

What version of the product are you using? On what operating system?
Current version for Mac 64 bit (OSX) and Droid Incredible 2.2

Please provide any additional information below.
Here is the log:
ERROR [BluetoothNotificationReceiver] - Error handling bluetooth notification
javax.bluetooth.BluetoothConnectionException: Failed to open connection(2) 
[0xe00002cd]
    at com.intel.bluetooth.BluetoothStackOSX.rfServerAcceptAndOpenRfServerConnection(Native Method)
    at com.intel.bluetooth.BluetoothRFCommConnectionNotifier.acceptAndOpen(BluetoothRFCommConnectionNotifier.java:74)
    at com.notifier.desktop.notification.bluetooth.BluetoothNotificationReceiver$1.run(BluetoothNotificationReceiver.java:83)
    at java.lang.Thread.run(Thread.java:637)
2010-10-11 13:24:47,956 DEBUG [bluetooth] - create ChannelController to accept 
incoming connection
2010-10-11 13:25:23,787 INFO [NotificationManagerImpl] - Pairing stopped
2010-10-11 13:25:23,787 INFO [NotificationManagerImpl] - Pairing stopped
2010-10-11 13:28:12,016 DEBUG [bluetooth] - will throw exception 
javax/bluetooth/BluetoothConnectionException(Failed to open connection(2) 
[0xe00002cd])
2010-10-11 13:28:12,100 ERROR [BluetoothNotificationReceiver] - Error handling 
bluetooth notification
javax.bluetooth.BluetoothConnectionException: Failed to open connection(2) 
[0xe00002cd]
    at com.intel.bluetooth.BluetoothStackOSX.rfServerAcceptAndOpenRfServerConnection(Native Method)
    at com.intel.bluetooth.BluetoothRFCommConnectionNotifier.acceptAndOpen(BluetoothRFCommConnectionNotifier.java:74)
    at com.notifier.desktop.notification.bluetooth.BluetoothNotificationReceiver$1.run(BluetoothNotificationReceiver.java:83)
    at java.lang.Thread.run(Thread.java:637)
2010-10-11 13:28:12,101 DEBUG [bluetooth] - create ChannelController to accept 
incoming connection


```

Original issue reported on code.google.com by `S.Willia...@gmail.com` on 11 Oct 2010 at 5:38
- Merged into: #3

**Comment by GoogleCodeExporter** [comment]
Original comment by `rdamazio@gmail.com` on 13 Oct 2010 at 3:14

**Comment by GoogleCodeExporter** [comment]
```
I see the same thing on a Samsung Epic 4G and Mac 64-bit OS X
```

Original comment by `mcgaffin` on 14 Oct 2010 at 5:27

**Comment by GoogleCodeExporter** [comment]
```
This is a known bluetooth issue in HTC and Samsung phones, issue 3 has more 
information.
```

Original comment by `lehph...@gmail.com` on 14 Oct 2010 at 6:34
- Changed state: **Duplicate**
- Added labels: **Component-Communication**, **OpSys-OSX**
