### ISSUE TITLE
Bluetooth Alerts throw an error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CarlitoBriganteNT/android-notifier#241]
```
IMPORTANT: PLEASE search the existing issues (including closed ones) for
something similar before filing a new one.

What steps will reproduce the problem?
1. Phone is paired and works with other bluetooth services with my mac.
2. Send test notification or any sort of sms, email, phone call, etc.

What is the expected output? What do you see instead?
I expect to see the growl notification, instead I see: "An error occurred while 
receiving bluetooth notification" in a dialog box.

What version of the product are you using? On what operating system?
Version 0.5 for Mac OSX 10.6.x
Version 2.1 of Android (Droid Eris)

Please provide the log output if possible (from the alogcat app on android,
Show Log menu on the multiplatform client, or Console on native mac app):

2010-10-17 16:32:49,366 DEBUG [bluetooth] - rfcomm (9) client connected
2010-10-17 16:32:49,367 DEBUG [bluetooth] - rfcomm MTU 1685
2010-10-17 16:32:49,367 DEBUG [bluetooth] - connection open, open now 1
2010-10-17 16:32:49,367 DEBUG [bluetooth] - ->read(byte[4096])
2010-10-17 16:32:49,504 DEBUG [bluetooth] - read([]) return 58
2010-10-17 16:32:49,505 DEBUG [bluetooth] - ->read(byte[4096])
2010-10-17 16:32:50,005 DEBUG [bluetooth] - read([]) received 0
2010-10-17 16:32:50,005 DEBUG [bluetooth] - read([]) no data
2010-10-17 16:32:50,006 DEBUG [bluetooth] - read([]) return EOF
2010-10-17 16:32:50,041 INFO [NotificationManagerImpl] - Notification received: 
notificationId=1280210632116294, type=Ping
2010-10-17 16:32:50,047 DEBUG [bluetooth] - closing RFCOMM Connection 9
2010-10-17 16:32:50,047 DEBUG [bluetooth] - connection closed, open now 0
2010-10-17 16:32:50,047 DEBUG [bluetooth] - create ChannelController to accept 
incoming connection
2010-10-17 16:33:01,554 DEBUG [bluetooth] - rfcomm (10) client connected
2010-10-17 16:33:01,555 DEBUG [bluetooth] - rfcomm MTU 1685
2010-10-17 16:33:01,556 DEBUG [bluetooth] - connection open, open now 1
2010-10-17 16:33:01,556 DEBUG [bluetooth] - ->read(byte[4096])
2010-10-17 16:33:02,502 DEBUG [bluetooth] - read([]) return 82
2010-10-17 16:33:02,502 DEBUG [bluetooth] - ->read(byte[4096])
2010-10-17 16:33:03,003 DEBUG [bluetooth] - read([]) received 0
2010-10-17 16:33:03,004 DEBUG [bluetooth] - read([]) no data
2010-10-17 16:33:03,004 DEBUG [bluetooth] - read([]) return EOF
2010-10-17 16:33:03,005 INFO [NotificationManagerImpl] - Notification received: 
notificationId=39686887690916556, type=Battery
2010-10-17 16:33:03,005 DEBUG [bluetooth] - closing RFCOMM Connection 10
2010-10-17 16:33:03,006 DEBUG [bluetooth] - connection closed, open now 0
2010-10-17 16:33:03,006 DEBUG [bluetooth] - create ChannelController to accept 
incoming connection
2010-10-17 16:33:06,508 DEBUG [bluetooth] - will throw exception 
javax/bluetooth/BluetoothConnectionException(Failed to open connection(3))
2010-10-17 16:33:06,509 ERROR [BluetoothNotificationReceiver] - Error handling 
bluetooth notification
javax.bluetooth.BluetoothConnectionException: Failed to open connection(3)
    at com.intel.bluetooth.BluetoothStackOSX.rfServerAcceptAndOpenRfServerConnection(Native Method)
    at com.intel.bluetooth.BluetoothRFCommConnectionNotifier.acceptAndOpen(BluetoothRFCommConnectionNotifier.java:74)
    at com.notifier.desktop.notification.bluetooth.BluetoothNotificationReceiver$1.run(BluetoothNotificationReceiver.java:83)
    at java.lang.Thread.run(Thread.java:637)
2010-10-17 16:33:06,510 DEBUG [bluetooth] - create ChannelController to accept 
incoming connection
2010-10-17 16:55:03,897 DEBUG [bluetooth] - will throw exception 
javax/bluetooth/BluetoothConnectionException(Failed to open connection(3))
2010-10-17 16:55:03,897 ERROR [BluetoothNotificationReceiver] - Error handling 
bluetooth notification
javax.bluetooth.BluetoothConnectionException: Failed to open connection(3)
    at com.intel.bluetooth.BluetoothStackOSX.rfServerAcceptAndOpenRfServerConnection(Native Method)
    at com.intel.bluetooth.BluetoothRFCommConnectionNotifier.acceptAndOpen(BluetoothRFCommConnectionNotifier.java:74)
    at com.notifier.desktop.notification.bluetooth.BluetoothNotificationReceiver$1.run(BluetoothNotificationReceiver.java:83)
    at java.lang.Thread.run(Thread.java:637)
2010-10-17 16:55:03,898 DEBUG [bluetooth] - create ChannelController to accept 
incoming connection
2010-10-17 16:56:11,945 DEBUG [bluetooth] - will throw exception 
javax/bluetooth/BluetoothConnectionException(Failed to open connection(3))
2010-10-17 16:56:11,995 ERROR [BluetoothNotificationReceiver] - Error handling 
bluetooth notification
javax.bluetooth.BluetoothConnectionException: Failed to open connection(3)
    at com.intel.bluetooth.BluetoothStackOSX.rfServerAcceptAndOpenRfServerConnection(Native Method)
    at com.intel.bluetooth.BluetoothRFCommConnectionNotifier.acceptAndOpen(BluetoothRFCommConnectionNotifier.java:74)
    at com.notifier.desktop.notification.bluetooth.BluetoothNotificationReceiver$1.run(BluetoothNotificationReceiver.java:83)
    at java.lang.Thread.run(Thread.java:637)
2010-10-17 16:56:11,995 DEBUG [bluetooth] - create ChannelController to accept 
incoming connection
2010-10-17 16:58:33,082 DEBUG [bluetooth] - will throw exception 
javax/bluetooth/BluetoothConnectionException(Failed to open connection(3))
2010-10-17 16:58:33,109 ERROR [BluetoothNotificationReceiver] - Error handling 
bluetooth notification
javax.bluetooth.BluetoothConnectionException: Failed to open connection(3)
    at com.intel.bluetooth.BluetoothStackOSX.rfServerAcceptAndOpenRfServerConnection(Native Method)
    at com.intel.bluetooth.BluetoothRFCommConnectionNotifier.acceptAndOpen(BluetoothRFCommConnectionNotifier.java:74)
    at com.notifier.desktop.notification.bluetooth.BluetoothNotificationReceiver$1.run(BluetoothNotificationReceiver.java:83)
    at java.lang.Thread.run(Thread.java:637)
2010-10-17 16:58:33,110 DEBUG [bluetooth] - create ChannelController to accept 
incoming connection

Please provide any additional information below.
Whenever any alert pops up on my phone, I get the bluetooth error described 
above on my phone.

The pairing between my phone and my computer work for other connections, but 
apparently not this one.
```

Original issue reported on code.google.com by `hess.sm...@gmail.com` on 18 Oct 2010 at 12:03
- Merged into: #3

**Comment by GoogleCodeExporter** [comment]
```
Leandro, perhaps we can do something to address the fact that this issue has 
been reported lots of times? Every 2-3 days we get a new report.
```

Original comment by `rdamazio@gmail.com` on 18 Oct 2010 at 12:08

**Comment by GoogleCodeExporter** [comment]
```
Perhaps we should disable bluetooth support until they fix bluetooth drivers in 
HTC devices? The android app can detect if it's running in an HTC device and 
disable the option, but it'll penalize Windows users because bluetooth does not 
work only on Mac and Linux. The native Mac app probably has the same issue.
```

Original comment by `lehph...@gmail.com` on 18 Oct 2010 at 12:30
- Added labels: **OpSys-OSX**

**Comment by GoogleCodeExporter** [comment]
```
I have an HTC phone and it works on all 3 OSs.
```

Original comment by `rdamazio@gmail.com` on 18 Oct 2010 at 3:48

**Comment by GoogleCodeExporter** [comment]
```
I have a Nexus One and it doesn't work on Ubuntu, almost all bluetooth issues 
happen on HTC phones connecting to Mac or Linux desktops, I've posted a link on 
issue 3 where an android developer says HTC is aware of this.
```

Original comment by `lehph...@gmail.com` on 18 Oct 2010 at 12:15

**Comment by GoogleCodeExporter** [comment]
```
All I can say is that it works for me and for a lot of people I've talked to, 
so if it works for at least part of the HTC phones, we shouldn't penalize those 
for whom it may be working fine.
```

Original comment by `rdamazio@gmail.com` on 18 Oct 2010 at 5:53

**Comment by GoogleCodeExporter** [comment]
```
I've put a warning in BluetoothHowto alerting HTC users that bluetooth 
communication may not work and they should see issue 3 for more info. Let's 
mark this issue duplicate of 3?
```

Original comment by `lehph...@gmail.com` on 18 Oct 2010 at 6:37

**Comment by GoogleCodeExporter** [comment]
```
Right, we can add the warning, but where did you see HTC admitting that it's 
their fault? 'cause people have reported this on other brands, too.
```

Original comment by `rdamazio@gmail.com` on 18 Oct 2010 at 9:27
- Changed state: **Duplicate**
