### ISSUE TITLE
Cannot set to start at login

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CarlitoBriganteNT/android-notifier#258]
```
I am using Ubuntu 10.10 64-bit desktop.  I installed 
android-notifier-desktop_0.5.1-0_amd64.deb which I downloaded from this 
website.  I successfully paired my phone with the software via WiFi.  When I 
attempted to configure the software to start at login, I got a dialog box with 
the message "An error ocurred while updating startup status."  The logs 
contained the following traceback:

2010-10-24 11:26:54,946 INFO [ApplicationImpl] - Adding to startup
2010-10-24 11:26:54,947 ERROR [ApplicationImpl] - Error adjusting startup
java.io.IOException: Could not find autostart directory
    at com.notifier.desktop.app.OperatingSystems.getLinuxStartupDir(OperatingSystems.java:250)
    at com.notifier.desktop.app.OperatingSystems.addToLinuxStartup(OperatingSystems.java:229)
    at com.notifier.desktop.app.OperatingSystems.addToStartup(OperatingSystems.java:60)
    at com.notifier.desktop.app.ApplicationImpl.adjustStartup(ApplicationImpl.java:292)
    at com.notifier.desktop.app.ApplicationImpl.adjustStartAtLogin(ApplicationImpl.java:124)
    at com.notifier.desktop.view.PreferencesDialog$2$1.run(PreferencesDialog.java:156)
    at java.lang.Thread.run(Thread.java:636)

Hope this helps!  Let me know if there's anything I can do to help debug the 
issue.
```

Original issue reported on code.google.com by `math...@gmail.com` on 24 Oct 2010 at 6:29
- Merged into: #222

**Comment by GoogleCodeExporter** [comment]
```
A jar file with the fix is available on issue 222.
```

Original comment by `lehph...@gmail.com` on 24 Oct 2010 at 6:34
- Changed state: **Duplicate**
- Added labels: **OpSys-Linux**

**Comment by GoogleCodeExporter** [comment]
```
I installed the jar file from issue 222 and now android-notifier-desktop no 
longer starts up.  Nothing is reflected in the log file.  Perhaps there's a 
32/64 bit issue with the jar file?
```

Original comment by `math...@gmail.com` on 24 Oct 2010 at 6:48

**Comment by GoogleCodeExporter** [comment]
```
Instead of using that jar file, you can just create the autostart directory 
with this command: mkdir  /home/your name/.config/autostart
```

Original comment by `lehph...@gmail.com` on 24 Oct 2010 at 8:20

**Comment by GoogleCodeExporter** [comment]
```
Issue 268 has been merged into this issue.
```

Original comment by `lehph...@gmail.com` on 28 Oct 2010 at 4:03
