### ISSUE TITLE
android-notifier requires java1.6, not 1.5

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CarlitoBriganteNT/android-notifier#260]
```
IMPORTANT: PLEASE search the existing issues (including closed ones) for
something similar before filing a new one.

What steps will reproduce the problem?
1. installed android-notifier-desktop_0.5.1-0_i386.deb, needed libnotify-bin 
and libbluetooth-dev, which aptitude found and installed.
2. tried it from Applications menu. nothing. Looked through .deb file to find 
that it installed /usr/share/android-notifier-desktop/run.sh
3. tried to run that directly.

What is the expected output? What do you see instead?
I expected a windows, or something.


What version of the product are you using? On what operating system?
I am running Debian Linux lenny with backports.  I have many versions of Java 
installed to satisfy many requirements.


Please provide the log output if possible (from the alogcat app on android,
Show Log menu on the multiplatform client, or Console on native mac app):


Please provide any additional information below.

marajade-[~/Desktop/Downloads] mcr 10074 
%/usr/share/android-notifier-desktop/run.sh &   
[2] 23751
marajade-[~/Desktop/Downloads] mcr 10075 %Exception in thread "main" 
java.lang.UnsupportedClassVersionError: Bad version number in .class file
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:124)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:260)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:56)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:195)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:268)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:252)
        at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:320)

marajade-[~/Desktop/Downloads] mcr 10079 %java -version 
java version "1.5.0_22"
Java(TM) 2 Runtime Environment, Standard Edition (build 1.5.0_22-b03)
Java HotSpot(TM) Client VM (build 1.5.0_22-b03, mixed mode, sharing)

I then tried using:
/usr/lib/jvm/java-6-sun/jre/bin/java

and it worked.


```

Original issue reported on code.google.com by `mcharl...@gmail.com` on 25 Oct 2010 at 2:34

**Comment by GoogleCodeExporter** [comment]
```
Yes, it requires Java 6 and it's one of its dependencies. Java 5 has reached 
end of service life at Oracle and the last release of it was almost a year ago. 
I think that if you use standard .deb files to install and upgrade java like 
any other program, java6 will be the system default and you'd have to run java5 
explicitly if you needed it.
```

Original comment by `lehph...@gmail.com` on 25 Oct 2010 at 12:09
- Changed state: **Done**
- Added labels: **OpSys-Desktop**

**Comment by GoogleCodeExporter** [comment]
```
if I let java6 be the default, I can't build android AOSP.
My opinion is that apps need to ask for the java that they need if they have 
dependancies.  I realize that this applies for AOSP too, and I'm pushing them 
too.

```

Original comment by `mcharl...@gmail.com` on 25 Oct 2010 at 3:58

**Comment by GoogleCodeExporter** [comment]
```
A java 6 compiler is able to compile source code to run in java 5 if you use 
the -target option see: 
http://download.oracle.com/javase/1.4.2/docs/tooldocs/windows/javac.html

The multiplatform app explicitly asks for Java6, here is the dependency 
declaration: sun-java6-jre | sun-java6-jdk | openjdk-6-jre | openjdk-6-jdk
```

Original comment by `lehph...@gmail.com` on 25 Oct 2010 at 4:10
