### ISSUE TITLE
Java traceback when trying to start with ./run.sh

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CarlitoBriganteNT/android-notifier#262]
```
I installed android-notifier-desktop_0.5.1-0_i386.deb on my Debian Linux system.

When I run /usr/share/android-notifier-desktop/run.sh, I get the following 
traceback:

java.lang.NoClassDefFoundError: 
com.google.inject.internal.cglib.core.DebuggingClassWriter$1
2010-10-25 20:27:47,808 ERROR [Main] - Error starting
com.google.inject.internal.ComputationException: 
java.lang.NoClassDefFoundError: 
com.google.inject.internal.cglib.core.DebuggingClassWriter$1
   at com.google.inject.internal.MapMaker$StrategyImpl.compute(MapMaker.java:553)
   at com.google.inject.internal.MapMaker$StrategyImpl.compute(MapMaker.java:419)
   at com.google.inject.internal.CustomConcurrentHashMap$ComputingImpl.get(CustomConcurrentHashMap.java:2041)
   at com.google.inject.internal.FailableCache.get(FailableCache.java:46)
   at com.google.inject.ConstructorInjectorStore.get(ConstructorInjectorStore.java:52)
   at com.google.inject.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:57)
   at com.google.inject.InjectorImpl.initializeBinding(InjectorImpl.java:377)
   at com.google.inject.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:645)
   at com.google.inject.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:581)
   at com.google.inject.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:172)
   at com.google.inject.InjectorImpl.getBindingOrThrow(InjectorImpl.java:132)
   at com.google.inject.InjectorImpl.getInternalFactory(InjectorImpl.java:651)
   at com.google.inject.FactoryProxy.notify(FactoryProxy.java:48)
   at com.google.inject.BindingProcessor.runCreationListeners(BindingProcessor.java:230)
   at com.google.inject.InjectorBuilder.initializeStatically(InjectorBuilder.java:131)
   at com.google.inject.InjectorBuilder.build(InjectorBuilder.java:105)
   at com.google.inject.Guice.createInjector(Guice.java:92)
   at com.google.inject.Guice.createInjector(Guice.java:80)
   at com.notifier.desktop.Main.main(Main.java:104)
Caused by: java.lang.NoClassDefFoundError: 
com.google.inject.internal.cglib.core.DebuggingClassWriter$1
   at java.lang.Class.initializeClass(libgcj.so.90)
   at com.google.inject.internal.cglib.core.DebuggingClassWriter.toByteArray(DebuggingClassWriter.java:71)
   at com.google.inject.internal.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:26)
   at com.google.inject.internal.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:216)
   at com.google.inject.internal.cglib.core.KeyFactory$Generator.create(KeyFactory.java:144)
   at com.google.inject.internal.cglib.core.KeyFactory.create(KeyFactory.java:116)
   at com.google.inject.internal.cglib.core.KeyFactory.create(KeyFactory.java:108)
   at com.google.inject.internal.cglib.core.KeyFactory.create(KeyFactory.java:104)
   at com.google.inject.internal.cglib.core.MethodWrapper.<clinit>(MethodWrapper.java:22)
   at java.lang.Class.initializeClass(libgcj.so.90)
   at com.google.inject.internal.cglib.core.DuplicatesPredicate.evaluate(DuplicatesPredicate.java:25)
   at com.google.inject.internal.cglib.core.CollectionUtils.filter(CollectionUtils.java:52)
   at com.google.inject.internal.cglib.reflect.FastClassEmitter.<init>(FastClassEmitter.java:69)
   at com.google.inject.internal.cglib.reflect.FastClass$Generator.generateClass(FastClass.java:72)
   at com.google.inject.internal.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
   at com.google.inject.internal.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:216)
   at com.google.inject.internal.cglib.reflect.FastClass$Generator.create(FastClass.java:64)
   at com.google.inject.internal.BytecodeGen.newFastClass(BytecodeGen.java:166)
   at com.google.inject.DefaultConstructionProxyFactory$1.<init>(DefaultConstructionProxyFactory.java:54)
   at com.google.inject.DefaultConstructionProxyFactory.create(DefaultConstructionProxyFactory.java:52)
   at com.google.inject.ProxyFactory.create(ProxyFactory.java:152)
   at com.google.inject.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:84)
   at com.google.inject.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:31)
   at com.google.inject.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:39)
   at com.google.inject.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:35)
   at com.google.inject.internal.FailableCache$1.apply(FailableCache.java:35)
   at com.google.inject.internal.MapMaker$StrategyImpl.compute(MapMaker.java:549)
   ...18 more
Caused by: java.lang.ClassNotFoundException: 
com.google.inject.internal.asm.util.TraceClassVisitor not found in 
gnu.gcj.runtime.SystemClassLoader{urls=[file:/usr/share/android-notifier-desktop
/android-notifier-desktop.jar], 
parent=gnu.gcj.runtime.ExtensionClassLoader{urls=[], parent=null}}
   at java.net.URLClassLoader.findClass(libgcj.so.90)
   at gnu.gcj.runtime.SystemClassLoader.findClass(libgcj.so.90)
   at java.lang.ClassLoader.loadClass(libgcj.so.90)
   at java.lang.ClassLoader.loadClass(libgcj.so.90)
   at java.lang.Class.forName(libgcj.so.90)
   at java.lang.Class.initializeClass(libgcj.so.90)
   ...44 more
```

Original issue reported on code.google.com by `jrdi...@gmail.com` on 26 Oct 2010 at 3:28

**Comment by GoogleCodeExporter** [comment]
```
Gcj does not work, please make sure the command java -version returns a Sun or 
OpenJDK jvm info.
```

Original comment by `lehph...@gmail.com` on 26 Oct 2010 at 3:36

**Comment by GoogleCodeExporter** [comment]
```
I've got the same issue (Debian Wheezy)

linmz@think:~$ java -version
java version "1.5.0"
gij (GNU libgcj) version 4.4.6

Any idea how to make it work ?


```

Original comment by `m.zwys...@gmail.com` on 7 Jun 2011 at 2:26

**Comment by GoogleCodeExporter** [comment]
```
Nevermind. Just install default-jre and its dependencies and it works as 
expected.
```

Original comment by `m.zwys...@gmail.com` on 7 Jun 2011 at 2:47
