### ISSUE TITLE
Start up at login error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CarlitoBriganteNT/android-notifier#268]
```
IMPORTANT: PLEASE search the existing issues (including closed ones) for
something similar before filing a new one.

What steps will reproduce the problem?
1.clicking start up at login in preferences
2.
3.

What is the expected output? What do you see instead?
error shows An error ocurred while updating startup status

What version of the product are you using? On what operating system?
android notifier desktop 0.5.1 on ubuntu 10.10 maverick meerkat

Please provide the log output if possible (from the alogcat app on android,
Show Log menu on the multiplatform client, or Console on native mac app):
2010-10-28 13:32:58,445 INFO [ApplicationImpl] - Adding to startup
2010-10-28 13:32:58,446 ERROR [ApplicationImpl] - Error adjusting startup
java.io.IOException: Could not find autostart directory
    at com.notifier.desktop.app.OperatingSystems.getLinuxStartupDir(OperatingSystems.java:250)
    at com.notifier.desktop.app.OperatingSystems.addToLinuxStartup(OperatingSystems.java:229)
    at com.notifier.desktop.app.OperatingSystems.addToStartup(OperatingSystems.java:60)
    at com.notifier.desktop.app.ApplicationImpl.adjustStartup(ApplicationImpl.java:292)
    at com.notifier.desktop.app.ApplicationImpl.adjustStartAtLogin(ApplicationImpl.java:124)
    at com.notifier.desktop.view.PreferencesDialog$2$1.run(PreferencesDialog.java:156)
    at java.lang.Thread.run(Thread.java:636)

Please provide any additional information below.

```

Original issue reported on code.google.com by `psychoc...@gmail.com` on 28 Oct 2010 at 12:34
- Merged into: #258

**Comment by GoogleCodeExporter** [comment]
Original comment by `lehph...@gmail.com` on 28 Oct 2010 at 4:03
- Changed state: **Duplicate**
- Added labels: **OpSys-Linux**

**Comment by GoogleCodeExporter** [comment]
```
thanks for that.

apologies about the dupe, i was sure i checked all ...
```

Original comment by `psychoc...@gmail.com` on 28 Oct 2010 at 4:19

**Comment by GoogleCodeExporter** [comment]
```
No problem, I just had no comment to add to this issue.
```

Original comment by `lehph...@gmail.com` on 28 Oct 2010 at 4:24
