### ISSUE TITLE
Bluetooth does not send updates

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CarlitoBriganteNT/android-notifier#283]
```
What steps will reproduce the problem?
1.  Pair phone with PC
2. Attempt to send test message.
3.  Message fails to be received by PC.

What is the expected output? What do you see instead?
Test message received correctly by PC

Please paste the application's log here (it should now be on your
clipboard):

D/RemoteNotifier(13453): Battery status: NOT charging
D/RemoteNotifier(13453): Got battery level: 72
D/RemoteNotifier(13453): Battery level change: 4
D/RemoteNotifier(13453): Got battery update, but state change was not relevant
D/RemoteNotifier(13453): Battery status: NOT charging
D/RemoteNotifier(13453): Got battery level: 72
D/RemoteNotifier(13453): Battery level change: 4
D/RemoteNotifier(13453): Got battery update, but state change was not relevant
D/RemoteNotifier(13453): Battery status: NOT charging
D/RemoteNotifier(13453): Got battery level: 71
D/RemoteNotifier(13453): Battery level change: 5
D/RemoteNotifier(13453): Notifying of battery state change
D/RemoteNotifier(13453): Sending notification: 
v2/9774d56d682e549c/831b12e5fcc61b/BATTERY/71/NOT charging, remaining charge: 
71%
D/BluetoothSocket.cpp(13453): initSocketNative
D/BluetoothSocket.cpp(13453): ...fd 39 created (RFCOMM, lm = 26)
D/BluetoothSocket.cpp(13453): initSocketFromFdNative
D/RemoteNotifier(13453): Connecting to Bluetooth device LT17643
I/BluetoothService.cpp( 6302): ... Object Path = 
/org/bluez/6598/hci0/dev_00_22_5F_95_E7_3C
I/BluetoothService.cpp( 6302): ... Pattern = 
7674047e-6e47-4bf0-831f-209e3f9dd23f, strlen = 36
I/BluetoothEventLoop.cpp( 6302): event_filter: Received signal 
org.bluez.Device:PropertyChanged from /org/bluez/6598/hci0/dev_00_22_5F_95_E7_3C
D/BluetoothEventLoop( 6302): Device property changed:00:22:5F:95:E7:3C 
property:Connected
I/BluetoothService( 6302): ACL connected, mAclLinkCount = 1
I/BluetoothEventLoop.cpp( 6302): event_filter: Received signal 
org.bluez.Device:PropertyChanged from /org/bluez/6598/hci0/dev_00_22_5F_95_E7_3C
D/BluetoothEventLoop( 6302): Device property changed:00:22:5F:95:E7:3C 
property:UUIDs
D/BluetoothService( 6302): updateDeviceServiceChannelCache(00:22:5F:95:E7:3C)
D/BluetoothService( 6302):  uuid(system): 00001108-0000-1000-8000-00805f9b34fb 
4360
D/BluetoothService( 6302):  uuid(application): 
7674047e-6e47-4bf0-831f-209e3f9dd23f 10
D/BluetoothService( 6302): Making callback for 
7674047e-6e47-4bf0-831f-209e3f9dd23f with result 10
D/BluetoothSocket.cpp(13453): connectNative
V/BluetoothEventRedirector(12340): Received android.bleutooth.device.action.UUID
D/BluetoothSocket.cpp(13453): ...connect(39, RFCOMM) = 0 (errno 0)
D/BluetoothSocket.cpp(13453): writeNative
D/BluetoothSocket.cpp(13453): abortNative
D/BluetoothSocket.cpp(13453): ...asocket_abort(39) complete
D/BluetoothSocket.cpp(13453): destroyNative
D/BluetoothSocket.cpp(13453): ...asocket_destroy(39) complete
D/RemoteNotifier(13453): Sent notification over Bluetooth (0 retries).
V/BluetoothEventRedirector(12340): Received android.bleutooth.device.action.UUID
I/BluetoothEventLoop.cpp( 6302): event_filter: Received signal 
org.bluez.Device:PropertyChanged from /org/bluez/6598/hci0/dev_00_22_5F_95_E7_3C
D/BluetoothEventLoop( 6302): Device property changed:00:22:5F:95:E7:3C 
property:Disconnected
I/BluetoothService( 6302): ACL disconnected, mAclLinkCount = 0
D/BluetoothA2dpService( 6302): Received intent Intent { 
act=android.bluetooth.device.action.ACL_DISCONNECTED (has extras) }
I/BluetoothHIDService( 6302): Received intent Intent { 
act=android.bluetooth.device.action.ACL_DISCONNECTED (has extras) }, device = 
00:22:5F:95:E7:3C
I/BluetoothHIDService( 6302):     ...ACL disconnected
D/RemoteNotifier(13453): Battery status: NOT charging
D/RemoteNotifier(13453): Got battery level: 71
D/RemoteNotifier(13453): Battery level change: 0
D/RemoteNotifier(13453): Got battery update, but state change was not relevant
D/RemoteNotifier(13453): Not starting service again
D/RemoteNotifier(13453): Battery status: NOT charging
D/RemoteNotifier(13453): Got battery level: 71
D/RemoteNotifier(13453): Battery level change: 0
D/RemoteNotifier(13453): Got battery update, but state change was not relevant
D/RemoteNotifier(13453): Read log
D/RemoteNotifier(13453): Battery status: NOT charging
D/RemoteNotifier(13453): Got battery level: 71
D/RemoteNotifier(13453): Battery level change: 0
D/RemoteNotifier(13453): Got battery update, but state change was not relevant
D/RemoteNotifier(13453): Battery status: NOT charging
D/RemoteNotifier(13453): Got battery level: 71
D/RemoteNotifier(13453): Battery level change: 0
D/RemoteNotifier(13453): Got battery update, but state change was not relevant
D/RemoteNotifier(13453): Battery status: NOT charging
D/RemoteNotifier(13453): Got battery level: 70
D/RemoteNotifier(13453): Battery level change: 1
D/RemoteNotifier(13453): Got battery update, but state change was not relevant
D/RemoteNotifier(13453): Battery status: NOT charging
D/RemoteNotifier(13453): Got battery level: 70
D/RemoteNotifier(13453): Battery level change: 1
D/RemoteNotifier(13453): Got battery update, but state change was not relevant
D/RemoteNotifier(13453): Battery status: NOT charging
D/RemoteNotifier(13453): Got battery level: 70
D/RemoteNotifier(13453): Battery level change: 1
D/RemoteNotifier(13453): Got battery update, but state change was not relevant
D/RemoteNotifier(13453): Battery status: NOT charging
D/RemoteNotifier(13453): Got battery level: 70
D/RemoteNotifier(13453): Battery level change: 1
D/RemoteNotifier(13453): Got battery update, but state change was not relevant
D/RemoteNotifier(13453): Battery status: NOT charging
D/RemoteNotifier(13453): Got battery level: 69
D/RemoteNotifier(13453): Battery level change: 2
D/RemoteNotifier(13453): Got battery update, but state change was not relevant
D/RemoteNotifier(13453): Not starting service again
D/RemoteNotifier(13453): Sending notification: 
v2/9774d56d682e549c/43aab6f2be96f/PING//Test notification
D/BluetoothSocket.cpp(13453): initSocketNative
D/BluetoothSocket.cpp(13453): ...fd 40 created (RFCOMM, lm = 26)
D/BluetoothSocket.cpp(13453): initSocketFromFdNative
D/RemoteNotifier(13453): Connecting to Bluetooth device LT17643
I/BluetoothService.cpp( 6302): ... Object Path = 
/org/bluez/6598/hci0/dev_00_22_5F_95_E7_3C
I/BluetoothService.cpp( 6302): ... Pattern = 
7674047e-6e47-4bf0-831f-209e3f9dd23f, strlen = 36
I/BluetoothEventLoop.cpp( 6302): event_filter: Received signal 
org.bluez.Device:PropertyChanged from /org/bluez/6598/hci0/dev_00_22_5F_95_E7_3C
D/BluetoothEventLoop( 6302): Device property changed:00:22:5F:95:E7:3C 
property:Connected
I/BluetoothService( 6302): ACL connected, mAclLinkCount = 1
I/BluetoothEventLoop.cpp( 6302): event_filter: Received signal 
org.bluez.Device:PropertyChanged from /org/bluez/6598/hci0/dev_00_22_5F_95_E7_3C
D/BluetoothEventLoop( 6302): Device property changed:00:22:5F:95:E7:3C 
property:UUIDs
D/BluetoothService( 6302): updateDeviceServiceChannelCache(00:22:5F:95:E7:3C)
D/BluetoothService( 6302):  uuid(system): 00001108-0000-1000-8000-00805f9b34fb 
4360
D/BluetoothService( 6302):  uuid(application): 
7674047e-6e47-4bf0-831f-209e3f9dd23f 10
D/BluetoothService( 6302): Making callback for 
7674047e-6e47-4bf0-831f-209e3f9dd23f with result 10
D/BluetoothSocket.cpp(13453): connectNative
V/BluetoothEventRedirector(12340): Received android.bleutooth.device.action.UUID
D/BluetoothSocket.cpp(13453): ...connect(40, RFCOMM) = 0 (errno 0)
D/BluetoothSocket.cpp(13453): writeNative
D/BluetoothSocket.cpp(13453): abortNative
D/BluetoothSocket.cpp(13453): ...asocket_abort(40) complete
D/BluetoothSocket.cpp(13453): destroyNative
D/BluetoothSocket.cpp(13453): ...asocket_destroy(40) complete
D/RemoteNotifier(13453): Sent notification over Bluetooth (0 retries).
I/BluetoothEventLoop.cpp( 6302): event_filter: Received signal 
org.bluez.Device:PropertyChanged from /org/bluez/6598/hci0/dev_00_22_5F_95_E7_3C
D/BluetoothEventLoop( 6302): Device property changed:00:22:5F:95:E7:3C 
property:Disconnected
I/BluetoothService( 6302): ACL disconnected, mAclLinkCount = 0
D/BluetoothA2dpService( 6302): Received intent Intent { 
act=android.bluetooth.device.action.ACL_DISCONNECTED (has extras) }
I/BluetoothHIDService( 6302): Received intent Intent { 
act=android.bluetooth.device.action.ACL_DISCONNECTED (has extras) }, device = 
00:22:5F:95:E7:3C
I/BluetoothHIDService( 6302):     ...ACL disconnected
V/BluetoothEventRedirector(12340): Received android.bleutooth.device.action.UUID
D/RemoteNotifier(13453): Read log
D/RemoteNotifier(13453): Battery status: NOT charging
D/RemoteNotifier(13453): Got battery level: 69
D/RemoteNotifier(13453): Battery level change: 2
D/RemoteNotifier(13453): Got battery update, but state change was not relevant
D/RemoteNotifier(13453): Battery status: NOT charging
D/RemoteNotifier(13453): Got battery level: 69
D/RemoteNotifier(13453): Battery level change: 2
D/RemoteNotifier(13453): Got battery update, but state change was not relevant
D/RemoteNotifier(13453): Battery status: NOT charging
D/RemoteNotifier(13453): Got battery level: 69
D/RemoteNotifier(13453): Battery level change: 2
D/RemoteNotifier(13453): Got battery update, but state change was not relevant
D/RemoteNotifier(13453): Not starting service again


What version of Android are you using?

```

Original issue reported on code.google.com by `jman1...@gmail.com` on 9 Nov 2010 at 7:13
- Merged into: #3

**Comment by GoogleCodeExporter** [comment]
```
Using Android 2.2 on Samsung Galaxy S - Desktop version 0.5.1 - the PC gives 
the following relevant portion from the log:

2010-11-09 11:13:01,421 DEBUG [bluetooth] - connection open, open now 1
2010-11-09 11:13:01,421 DEBUG [bluetooth] - rf(8) read(byte[4096])
2010-11-09 11:13:01,421 DEBUG [bluetooth] - read[] waits for data
2010-11-09 11:13:01,453 DEBUG [bluetooth] - read waits returns WAIT_OBJECT_0
2010-11-09 11:13:01,453 DEBUG [bluetooth] - read waits returns WAIT_OBJECT_0
2010-11-09 11:13:01,453 DEBUG [bluetooth] - rf(8) read([]) received 0
2010-11-09 11:13:01,453 DEBUG [bluetooth] - rf(8) read([]) not connected
2010-11-09 11:13:01,453 DEBUG [bluetooth] - read([]) no data
2010-11-09 11:13:01,453 DEBUG [bluetooth] - read([]) return EOF
2010-11-09 11:13:01,453 ERROR [BluetoothNotificationReceiver] - Error handling 
bluetooth notification
com.notifier.desktop.exception.ParseException: 
com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol 
message, the input ended unexpectedly in the middle of a field.  This could 
mean either than the input has been truncated or that an embedded message 
misreported its own length.
    at com.notifier.desktop.parsing.MultiNotificationParser.parse(MultiNotificationParser.java:53)
    at com.notifier.desktop.parsing.MultiNotificationParser.parse(MultiNotificationParser.java:27)
    at com.notifier.desktop.notification.bluetooth.BluetoothNotificationReceiver$1.run(BluetoothNotificationReceiver.java:87)
    at java.lang.Thread.run(Unknown Source)
Caused by: com.google.protobuf.InvalidProtocolBufferException: While parsing a 
protocol message, the input ended unexpectedly in the middle of a field.  This 
could mean either than the input has been truncated or that an embedded message 
misreported its own length.
    at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:49)
    at com.google.protobuf.CodedInputStream.refillBuffer(CodedInputStream.java:691)
    at com.google.protobuf.CodedInputStream.readRawByte(CodedInputStream.java:714)
    at com.google.protobuf.CodedInputStream.readRawVarint32(CodedInputStream.java:318)
    at com.notifier.desktop.parsing.MultiNotificationParser.parse(MultiNotificationParser.java:42)
    ... 3 more
2010-11-09 11:13:01,453 DEBUG [bluetooth] - closing RFCOMM Connection 8
2010-11-09 11:13:01,453 DEBUG [bluetooth] - connection closed, open now 0
2010-11-09 11:13:01,453 DEBUG [bluetooth] - rf(8) CloseServerConnection
2010-11-09 11:13:01,453 DEBUG [bluetooth] - rf(8) closing RfCommPort, 
Connected[FALSE]
2010-11-09 11:13:01,515 DEBUG [bluetooth] - rf(8) closed RfCommPort
```

Original comment by `jman1...@gmail.com` on 9 Nov 2010 at 7:15

**Comment by GoogleCodeExporter** [comment]
```
PC is using WIDCOMM Bluetooth software 5.5.0.3208
```

Original comment by `jman1...@gmail.com` on 9 Nov 2010 at 7:16

**Comment by GoogleCodeExporter** [comment]
```
You are not the first one to report this, it seems Samsung Galaxy S phones 
don't send bluetooth messages correctly. Updated wiki page.
```

Original comment by `lehph...@gmail.com` on 9 Nov 2010 at 7:41
- Changed state: **Duplicate**
- Added labels: **Component-Communication**, **OpSys-Android**, **Priority-Medium**, **Type-Defect**

**Comment by GoogleCodeExporter** [comment]
```
Issue 289 has been merged into this issue.
```

Original comment by `lehph...@gmail.com` on 15 Nov 2010 at 1:32

**Comment by GoogleCodeExporter** [comment]
```
Problem occurred in 2.2, I was using SGS with AND on anrdoid 2.1 and it was 
working correctly
```

Original comment by `jaroslaw...@gmail.com` on 20 Jan 2011 at 2:49
