### ISSUE TITLE
Bluetooth notification failed

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CarlitoBriganteNT/android-notifier#289]
```
Just upgraded to 0.5.1. Droid is a Samsung Galaxy S with 2.2:

What steps will reproduce the problem?
1. run android-notifier-desktop
2. receive an trigger for a notification on the droid

What is the expected output? What do you see instead?
Error Message: Bluetooth notification failed

What version of the product are you using? On what operating system?
-newest droid version
-0.5.1 on amd64

Please provide the log output if possible (from the alogcat app on android,
Show Log menu on the multiplatform client, or Console on native mac app):

This "SMS Notification fails"
http://bu2010-11-15 11:05:46,016 DEBUG [bluetooth] - RFCOMM client accepted, 
handle 40
2010-11-15 11:05:46,016 DEBUG [bluetooth] - connection open, open now 1
2010-11-15 11:05:46,017 DEBUG [bluetooth] - no data available for read
2010-11-15 11:05:46,035 DEBUG [bluetooth] - Stream socket peer closed connection
2010-11-15 11:05:46,036 ERROR [BluetoothNotificationReceiver] - Error handling 
bluetooth notification
com.notifier.desktop.exception.ParseException: 
com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol 
message, the input ended unexpectedly in the middle of a field.  This could 
mean either than the input has been truncated or that an embedded message 
misreported its own length.
    at com.notifier.desktop.parsing.MultiNotificationParser.parse(MultiNotificationParser.java:53)
    at com.notifier.desktop.parsing.MultiNotificationParser.parse(MultiNotificationParser.java:27)
    at com.notifier.desktop.notification.bluetooth.BluetoothNotificationReceiver$1.run(BluetoothNotificationReceiver.java:87)
    at java.lang.Thread.run(Thread.java:662)
Caused by: com.google.protobuf.InvalidProtocolBufferException: While parsing a 
protocol message, the input ended unexpectedly in the middle of a field.  This 
could mean either than the input has been truncated or that an embedded message 
misreported its own length.
    at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:49)
    at com.google.protobuf.CodedInputStream.refillBuffer(CodedInputStream.java:691)
    at com.google.protobuf.CodedInputStream.readRawByte(CodedInputStream.java:714)
    at com.google.protobuf.CodedInputStream.readRawVarint32(CodedInputStream.java:318)
    at com.notifier.desktop.parsing.MultiNotificationParser.parse(MultiNotificationParser.java:42)
    ... 3 more
2010-11-15 11:05:46,037 DEBUG [bluetooth] - closing RFCOMM Connection 40
2010-11-15 11:05:46,038 DEBUG [bluetooth] - connection closed, open now 0
2010-11-15 11:05:46,038 DEBUG [bluetooth] - RFCOMM disconnect, handle 40

This Test Message is OK:
2010-11-15 11:12:17,695 DEBUG [bluetooth] - RFCOMM client accepted, handle 40
2010-11-15 11:12:17,695 DEBUG [bluetooth] - connection open, open now 1
2010-11-15 11:12:17,696 DEBUG [bluetooth] - no data available for read
2010-11-15 11:12:17,777 DEBUG [bluetooth] - no data available for read
2010-11-15 11:12:17,779 DEBUG [bluetooth] - Stream socket peer closed connection
2010-11-15 11:12:17,780 INFO [NotificationManagerImpl] - Notification received: 
notificationId=1261360120287943, type=Ping
2010-11-15 11:12:17,786 DEBUG [bluetooth] - closing RFCOMM Connection 40
2010-11-15 11:12:17,787 DEBUG [bluetooth] - connection closed, open now 0
2010-11-15 11:12:17,788 DEBUG [bluetooth] - RFCOMM disconnect, handle 40
gs.gentoo.org/show_bug.cgi?id=341659


```

Original issue reported on code.google.com by `fschm...@gmail.com` on 15 Nov 2010 at 10:22
- Merged into: #283

**Comment by GoogleCodeExporter** [comment]
Original comment by `rdamazio@gmail.com` on 15 Nov 2010 at 10:35

**Comment by GoogleCodeExporter** [comment]
Original comment by `lehph...@gmail.com` on 15 Nov 2010 at 1:32
- Changed state: **Duplicate**
