### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Cannot load 32-bit SWT libraries on 64-bit JVM

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CarlitoBriganteNT/android-notifier#291]
```
When launching MultiDroidNotifier 0.5.1 on a MacPro running 10.5.8, you get an 
error about running 32-bit JVM on a 64-bit OS (see attached).

According to 
http://ysasaki600.wordpress.com/2009/09/19/week2-tutorial-for-eclipse-wtp/, you 
need to pass the “-d32″ in VM argument field to force 32-bit rather than 
64-bit.

Launching via Terminal you get:

2010-11-16 01:10:06,073 INFO [ApplicationImpl] - Starting SWT
2010-11-16 01:10:06,109 ERROR [ApplicationImpl] - Error starting SWT
java.lang.UnsatisfiedLinkError: Cannot load 32-bit SWT libraries on 64-bit JVM
    at org.eclipse.swt.internal.Library.loadLibrary(Unknown Source)
    at org.eclipse.swt.internal.Library.loadLibrary(Unknown Source)
    at org.eclipse.swt.internal.C.<clinit>(Unknown Source)
    at org.eclipse.swt.internal.cocoa.NSThread.isMainThread(Unknown Source)
    at org.eclipse.swt.graphics.Device.<init>(Unknown Source)
    at org.eclipse.swt.widgets.Display.<init>(Unknown Source)
    at org.eclipse.swt.widgets.Display.<init>(Unknown Source)
    at com.notifier.desktop.app.SwtManagerImpl.start(SwtManagerImpl.java:44)
    at com.notifier.desktop.app.ApplicationImpl.start(ApplicationImpl.java:69)
    at com.notifier.desktop.Main.main(Main.java:106)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at apple.launcher.LaunchRunner.run(LaunchRunner.java:115)
    at apple.launcher.LaunchRunner.callMain(LaunchRunner.java:50)
    at apple.launcher.JavaApplicationLauncher.launch(JavaApplicationLauncher.java:52)
2010-11-16 01:10:06.466 JavaApplicationStub[14211:10b] [Java CocoaComponent 
compatibility mode]: Enabled
2010-11-16 01:10:06.467 JavaApplicationStub[14211:10b] [Java CocoaComponent 
compatibility mode]: Setting timeout for SWT to 0.100000
2010-11-16 01:10:07.114 JavaApplicationStub[14211:d903] *** -[NSConditionLock 
unlock]: lock (<NSConditionLock: 0x100143e20> '(null)') unlocked when not locked
2010-11-16 01:10:07.114 JavaApplicationStub[14211:d903] *** Break on 
_NSLockError() to debug.
2010-11-16 01:10:07.216 JavaApplicationStub[14211:d903] *** -[NSConditionLock 
unlock]: lock (<NSConditionLock: 0x12a92ce50> '(null)') unlocked when not locked
2010-11-16 01:10:07.217 JavaApplicationStub[14211:d903] *** Break on 
_NSLockError() to debug.


```

Original issue reported on code.google.com by `dar...@gmail.com` on 16 Nov 2010 at 9:11

Attachments:
- [error.png](https://storage.googleapis.com/google-code-attachments/android-notifier/issue-291/comment-0/error.png)

**Comment by GoogleCodeExporter** [comment]
```
java version "1.5.0_26"
Java(TM) 2 Runtime Environment, Standard Edition (build 1.5.0_26-b03-376-9M3263)
Java HotSpot(TM) Client VM (build 1.5.0_26-156, mixed mode, sharing)

```

Original comment by `dar...@gmail.com` on 16 Nov 2010 at 9:13

**Comment by GoogleCodeExporter** [comment]
```
You have to download the 64 bit version.
```

Original comment by `lehph...@gmail.com` on 16 Nov 2010 at 12:09

**Comment by GoogleCodeExporter** [comment]
```
doh.  didn't even see that download.
```

Original comment by `dar...@gmail.com` on 16 Nov 2010 at 12:14

**Comment by GoogleCodeExporter** [comment]
```
No problem.
```

Original comment by `lehph...@gmail.com` on 16 Nov 2010 at 12:17
- Changed state: **Done**
- Added labels: **OpSys-OSX**
