### ISSUE TITLE
Bluetooth Error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CarlitoBriganteNT/android-notifier#296]
```
IMPORTANT: PLEASE search the existing issues (including closed ones) for
something similar before filing a new one.

What steps will reproduce the problem?
1. Setup bluetooth notifications
2. Send test notification
3.

What is the expected output? What do you see instead?

Receive notification on mac.  Instead I get "An error ocurred while receiving 
bluetooth notification" Log error:

010-11-23 21:11:51,726 DEBUG [bluetooth] - create ChannelController to accept 
incoming connection
2010-11-23 21:12:07,604 INFO [NotificationManagerImpl] - Waiting for test 
notification to pair device
2010-11-23 21:12:16,235 DEBUG [bluetooth] - will throw exception 
javax/bluetooth/BluetoothConnectionException(Failed to open connection(2) 
[0xe00002cd])
2010-11-23 21:12:16,312 ERROR [BluetoothNotificationReceiver] - Error handling 
bluetooth notification
javax.bluetooth.BluetoothConnectionException: Failed to open connection(2) 
[0xe00002cd]
    at com.intel.bluetooth.BluetoothStackOSX.rfServerAcceptAndOpenRfServerConnection(Native Method)
    at com.intel.bluetooth.BluetoothRFCommConnectionNotifier.acceptAndOpen(BluetoothRFCommConnectionNotifier.java:74)
    at com.notifier.desktop.notification.bluetooth.BluetoothNotificationReceiver$1.run(BluetoothNotificationReceiver.java:83)
    at java.lang.Thread.run(Thread.java:680)

What version of the product are you using? On what operating system?

Desktop 0.5.1 64-bit
Android 0.2.8

Please provide the log output if possible (from the alogcat app on android,
Show Log menu on the multiplatform client, or Console on native mac app):


Please provide any additional information below.

```

Original issue reported on code.google.com by `andrew.rapp@gmail.com` on 24 Nov 2010 at 5:21
- Merged into: #208

**Comment by GoogleCodeExporter** [comment]
```
Phone is Samsung Captivate running 2.1-update1
```

Original comment by `andrew.rapp@gmail.com` on 24 Nov 2010 at 5:23

**Comment by GoogleCodeExporter** [comment]
Original comment by `rdamazio@gmail.com` on 24 Nov 2010 at 10:50
- Changed state: **Duplicate**
