### ISSUE TITLE
Prblem with bluetooth module

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CarlitoBriganteNT/android-notifier#30]
```
What steps will reproduce the problem?
1.Download the program with svn
2.Run
3.Can't load the bluetooth module

What is the expected output? What do you see instead?
./lindroidnotifier.py 
Traceback (most recent call last):
  File "./lindroidnotifier.py", line 13, in <module>
    from manager import NotificationManager
  File "/home/paolo/android-notifier-read-only/LinDroidNotifier/androidnotifier/manager.py", line 18, in <module>
    from listeners.rfcomm import BluetoothListener
  File "/home/paolo/android-notifier-read-only/LinDroidNotifier/androidnotifier/listeners/rfcomm.py", line 9, in <module>
    import bluetooth
ImportError: No module named bluetooth


What version of the product are you using? On what operating system?
Linux 64 bit

Please provide any additional information below.

```

Original issue reported on code.google.com by `pablosproject` on 5 Aug 2010 at 8:38

**Comment by GoogleCodeExporter** [comment]
```
I think you just need to install the bluetooth module for python, but I'll let 
William comment.
```

Original comment by `rdamazio@gmail.com` on 5 Aug 2010 at 9:19
- Added labels: **Component-Communication**, **OpSys-Linux**, **Stability**

**Comment by GoogleCodeExporter** [comment]
```
Rodrigo is right; Android Notifier for Linux depends on PyBluez. Installing the 
python-bluez package on Ubuntu should fix the problem for you.
```

Original comment by `wcauch...@gmail.com` on 5 Aug 2010 at 11:13

**Comment by GoogleCodeExporter** [comment]
```
So I'm closing this as it's not a real issue.
We do need to write proper docs for the linux version, though :)
Hopefully when we release a .deb/.rpm/etc file, it'll have the proper 
dependencies for install.
```

Original comment by `rdamazio@gmail.com` on 7 Aug 2010 at 1:34
- Changed state: **Invalid**
