### ISSUE TITLE
When checking off "Start at login" get an error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CarlitoBriganteNT/android-notifier#332]
```
What steps will reproduce the problem?
1. Open the Android Notifier Preferences
2. Left click the "Start at login" checkbox
3. Get a popup error "An error occurred while updating startup status".  I can 
click OK on the error, and I am brought back to the preferences, with the 
checkbox still unchecked.

What version of the product are you using? On what operating system?

Notifier 0.5.1 on Ubuntu 10.10 x64

Please provide the log output if possible (from the alogcat app on android,
Show Log menu on the multiplatform client, or Console on native mac app):

(Entire log file avail upon request, but I think these are the relevant lines)

2011-01-03 09:07:06,632 INFO [ApplicationImpl] - Adding to startup
2011-01-03 09:07:06,632 ERROR [ApplicationImpl] - Error adjusting startup
java.io.IOException: Could not find autostart directory
    at com.notifier.desktop.app.OperatingSystems.getLinuxStartupDir(OperatingSystems.java:250)
    at com.notifier.desktop.app.OperatingSystems.addToLinuxStartup(OperatingSystems.java:229)
    at com.notifier.desktop.app.OperatingSystems.addToStartup(OperatingSystems.java:60)
    at com.notifier.desktop.app.ApplicationImpl.adjustStartup(ApplicationImpl.java:292)
    at com.notifier.desktop.app.ApplicationImpl.adjustStartAtLogin(ApplicationImpl.java:124)
    at com.notifier.desktop.view.PreferencesDialog$2$1.run(PreferencesDialog.java:156)
    at java.lang.Thread.run(Thread.java:636)
2011-01-03 09:09:32,776 INFO [ApplicationImpl] - Adding to startup
2011-01-03 09:09:32,776 ERROR [ApplicationImpl] - Error adjusting startup
java.io.IOException: Could not find autostart directory
    at com.notifier.desktop.app.OperatingSystems.getLinuxStartupDir(OperatingSystems.java:250)
    at com.notifier.desktop.app.OperatingSystems.addToLinuxStartup(OperatingSystems.java:229)
    at com.notifier.desktop.app.OperatingSystems.addToStartup(OperatingSystems.java:60)
    at com.notifier.desktop.app.ApplicationImpl.adjustStartup(ApplicationImpl.java:292)
    at com.notifier.desktop.app.ApplicationImpl.adjustStartAtLogin(ApplicationImpl.java:124)
    at com.notifier.desktop.view.PreferencesDialog$2$1.run(PreferencesDialog.java:156)
    at java.lang.Thread.run(Thread.java:636)


Please provide any additional information below.

```

Original issue reported on code.google.com by `alapi...@gmail.com` on 3 Jan 2011 at 3:11

**Comment by GoogleCodeExporter** [comment]
```
Please, see issue 258, and try :
mkdir  /home/your name/.config/autostart
```

Original comment by `laurent....@gmail.com` on 6 Mar 2011 at 11:50
