### ISSUE TITLE
Notifier doesn't recognize Growl after sleep

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CarlitoBriganteNT/android-notifier#338]
```

What steps will reproduce the problem?
1. Configure Growl and Android notifier work together.
2. Test that Android notifications come out of Growl
3. Sleep the computer

What is the expected output? What do you see instead?

Notifications should come through Growl again, but instead, Android notifier 
informs me that "Growl is not running".


What version of the product are you using? On what operating system?
Android Notifier desktop 0.5.1 on Windows 7 x86


The logs just say it can't connect to GNTP server:

2011-01-17 08:10:54,049 ERROR [GrowlNotificationBroadcaster] - Error 
communicating with GNTP server
java.net.ConnectException: Connection refused: no further information
    at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
    at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
    at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.connect(NioClientSocketPipelineSink.java:384)
    at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processSelectedKeys(NioClientSocketPipelineSink.java:354)
    at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:276)
    at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

Please provide any additional information below.

I'm trying a workaround by restarting android notifier whenever i unlock my 
workstation.

```

Original issue reported on code.google.com by `sal...@gmail.com` on 17 Jan 2011 at 6:18

**Comment by GoogleCodeExporter** [comment]
```
i am having the same issue here
```

Original comment by `yorgos...@gmail.com` on 7 May 2011 at 1:06

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Same here. Is this application supported anymore?
```

Original comment by `and...@gmail.com` on 28 Mar 2012 at 6:59
