### ISSUE TITLE
PC says error when i select bluetooth option in desktop notifier preferences

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CarlitoBriganteNT/android-notifier#373]
```
IMPORTANT: PLEASE search the existing issues (including closed ones) for
something similar before filing a new one.

DO NOT, I repeat, DO NOT file more duplicates of issue 3 (bluetooth
notifications not working).

What steps will reproduce the problem?
1.
2.
3.

What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?

desktop 0.5.1, windows xp
Please provide the log output if possible (from the alogcat app on android,
Error
com.android.bluettothstack toshiba.getlibraryversion

Show Log menu on the multiplatform client, or Console on native mac app):


Please provide any additional information below.

```

Original issue reported on code.google.com by `krarv...@gmail.com` on 24 Mar 2011 at 7:00

**Comment by GoogleCodeExporter** [comment]
```
I am having the same issue.

Droid X non-rooted running Froyo

Version 0.5.1.

Windows XP

Here is the error from the log:

2011-03-31 09:29:59,037 ERROR [ApplicationImpl] - Error starting [bluetooth] 
receiver
java.lang.UnsatisfiedLinkError: 
com.intel.bluetooth.BluetoothStackToshiba.getLibraryVersion()I
    at com.intel.bluetooth.BluetoothStackToshiba.getLibraryVersion(Native Method)
    at com.intel.bluetooth.BlueCoveImpl.setBluetoothStack(BlueCoveImpl.java:964)
    at com.intel.bluetooth.BlueCoveImpl.detectStack(BlueCoveImpl.java:502)
    at com.intel.bluetooth.BlueCoveImpl.access$500(BlueCoveImpl.java:69)
    at com.intel.bluetooth.BlueCoveImpl$1.run(BlueCoveImpl.java:1044)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.intel.bluetooth.BlueCoveImpl.detectStackPrivileged(BlueCoveImpl.java:1042)
    at com.intel.bluetooth.BlueCoveImpl.getBluetoothStack(BlueCoveImpl.java:1035)
    at javax.bluetooth.LocalDevice.getLocalDeviceInstance(LocalDevice.java:75)
    at javax.bluetooth.LocalDevice.getLocalDevice(LocalDevice.java:95)
    at com.notifier.desktop.notification.bluetooth.BluetoothNotificationReceiver.doStart(BluetoothNotificationReceiver.java:54)
    at com.notifier.desktop.app.AbstractLifecycle.start(AbstractLifecycle.java:36)
    at com.notifier.desktop.app.ApplicationImpl.startLifecycle(ApplicationImpl.java:256)
    at com.notifier.desktop.app.ApplicationImpl.adjustLifecycle(ApplicationImpl.java:310)
    at com.notifier.desktop.app.ApplicationImpl.adjustBluetoothReceiver(ApplicationImpl.java:143)
    at com.notifier.desktop.view.PreferencesDialog$7$1.run(PreferencesDialog.java:320)
    at java.lang.Thread.run(Unknown Source)

```

Original comment by `jhw...@gmail.com` on 31 Mar 2011 at 4:19

**Comment by GoogleCodeExporter** [comment]
```
This is a problem with the Toshiba Bluetooth Stack.
I followed the method found here: 
http://code.google.com/p/androideasysms/issues/detail?id=33

Now it works :)
```

Original comment by `per.henr...@gmail.com` on 15 Dec 2011 at 10:30

**Comment by GoogleCodeExporter** [comment]
```
I just got same error (Toshiba bluetooth)
Desktop 0.5.1
App 0.2.8
```

Original comment by `cyclops4...@gmail.com` on 25 May 2015 at 10:16
