### ISSUE TITLE
Setup problem

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CarlitoBriganteNT/android-notifier#415]
```
What steps will reproduce the problem?
1.
2.
3.

What is the expected output? What do you see instead?


Please paste the application's log here (it should now be on your
clipboard):

 E/WifiService( 2680): Multicaster binderDied
I/InputManager-Callbacks( 2680): No input device calibration properties found 
for device AVRCP.
I/CallOnGoingView( 2794): onAttachedToWindow
I/CallOnGoingView( 2794): onDetachedFromWindow
I/CallOnGoingView( 2794): onAttachedToWindow
I/CallOnGoingView( 2794): onDetachedFromWindow
E/WifiService( 2680): Multicaster binderDied
E/AndroidRuntime(31856): FATAL EXCEPTION: main
E/AndroidRuntime(31856): java.lang.RuntimeException: Unable to instantiate 
application android.app.Application: java.lang.NullPointerException
E/AndroidRuntime(31856):    at 
android.app.LoadedApk.makeApplication(LoadedApk.java:466)
E/AndroidRuntime(31856):    at 
android.app.ActivityThread.handleBindApplication(ActivityThread.java:3268)
E/AndroidRuntime(31856):    at 
android.app.ActivityThread.access$2200(ActivityThread.java:117)
E/AndroidRuntime(31856):    at 
android.app.ActivityThread$H.handleMessage(ActivityThread.java:973)
E/AndroidRuntime(31856):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(31856):    at android.os.Looper.loop(Looper.java:123)
E/AndroidRuntime(31856):    at 
android.app.ActivityThread.main(ActivityThread.java:3691)
E/AndroidRuntime(31856):    at java.lang.reflect.Method.invokeNative(Native 
Method)
E/AndroidRuntime(31856):    at java.lang.reflect.Method.invoke(Method.java:507)
E/AndroidRuntime(31856):    at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:847)
E/AndroidRuntime(31856):    at 
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:605)
E/AndroidRuntime(31856):    at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(31856): Caused by: java.lang.NullPointerException
E/AndroidRuntime(31856):    at 
android.app.LoadedApk.initializeJavaContextClassLoader(LoadedApk.java:346)
E/AndroidRuntime(31856):    at 
android.app.LoadedApk.getClassLoader(LoadedApk.java:291)
E/AndroidRuntime(31856):    at 
android.app.LoadedApk.makeApplication(LoadedApk.java:458)
E/AndroidRuntime(31856):    ... 11 more
E/AndroidRuntime(31856): Error reporting crash
E/AndroidRuntime(31856): java.lang.IllegalArgumentException: Unknown package: 
org.damazio.notifier
E/AndroidRuntime(31856):    at android.os.Parcel.readException(Parcel.java:1326)
E/AndroidRuntime(31856):    at android.os.Parcel.readException(Parcel.java:1276)
E/AndroidRuntime(31856):    at 
android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.ja
va:2548)
E/AndroidRuntime(31856):    at 
com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeIni
t.java:87)
E/AndroidRuntime(31856):    at 
java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:854)
E/AndroidRuntime(31856):    at 
java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:851)
E/AndroidRuntime(31856):    at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(31863): FATAL EXCEPTION: main
E/AndroidRuntime(31863): java.lang.RuntimeException: Unable to instantiate 
application android.app.Application: java.lang.NullPointerException
E/AndroidRuntime(31863):    at 
android.app.LoadedApk.makeApplication(LoadedApk.java:466)
E/AndroidRuntime(31863):    at 
android.app.ActivityThread.handleBindApplication(ActivityThread.java:3268)
E/AndroidRuntime(31863):    at 
android.app.ActivityThread.access$2200(ActivityThread.java:117)
E/AndroidRuntime(31863):    at 
android.app.ActivityThread$H.handleMessage(ActivityThread.java:973)
E/AndroidRuntime(31863):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(31863):    at android.os.Looper.loop(Looper.java:123)
E/AndroidRuntime(31863):    at 
android.app.ActivityThread.main(ActivityThread.java:3691)
E/AndroidRuntime(31863):    at java.lang.reflect.Method.invokeNative(Native 
Method)
E/AndroidRuntime(31863):    at java.lang.reflect.Method.invoke(Method.java:507)
E/AndroidRuntime(31863):    at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:847)
E/AndroidRuntime(31863):    at 
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:605)
E/AndroidRuntime(31863):    at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(31863): Caused by: java.lang.NullPointerException
E/AndroidRuntime(31863):    at 
android.app.LoadedApk.initializeJavaContextClassLoader(LoadedApk.java:346)
E/AndroidRuntime(31863):    at 
android.app.LoadedApk.getClassLoader(LoadedApk.java:291)
E/AndroidRuntime(31863):    at 
android.app.LoadedApk.makeApplication(LoadedApk.java:458)
E/AndroidRuntime(31863):    ... 11 more
E/AndroidRuntime(31863): Error reporting crash
E/AndroidRuntime(31863): java.lang.IllegalArgumentException: Unknown package: 
org.damazio.notifier
E/AndroidRuntime(31863):    at android.os.Parcel.readException(Parcel.java:1326)
E/AndroidRuntime(31863):    at android.os.Parcel.readException(Parcel.java:1276)
E/AndroidRuntime(31863):    at 
android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.ja
va:2548)
E/AndroidRuntime(31863):    at 
com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeIni
t.java:87)
E/AndroidRuntime(31863):    at 
java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:854)
E/AndroidRuntime(31863):    at 
java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:851)
E/AndroidRuntime(31863):    at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(31870): FATAL EXCEPTION: main
E/AndroidRuntime(31870): java.lang.RuntimeException: Unable to instantiate 
application android.app.Application: java.lang.NullPointerException
E/AndroidRuntime(31870):    at 
android.app.LoadedApk.makeApplication(LoadedApk.java:466)
E/AndroidRuntime(31870):    at 
android.app.ActivityThread.handleBindApplication(ActivityThread.java:3268)
E/AndroidRuntime(31870):    at 
android.app.ActivityThread.access$2200(ActivityThread.java:117)
E/AndroidRuntime(31870):    at 
android.app.ActivityThread$H.handleMessage(ActivityThread.java:973)
E/AndroidRuntime(31870):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(31870):    at android.os.Looper.loop(Looper.java:123)
E/AndroidRuntime(31870):    at 
android.app.ActivityThread.main(ActivityThread.java:3691)
E/AndroidRuntime(31870):    at java.lang.reflect.Method.invokeNative(Native 
Method)
E/AndroidRuntime(31870):    at java.lang.reflect.Method.invoke(Method.java:507)
E/AndroidRuntime(31870):    at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:847)
E/AndroidRuntime(31870):    at 
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:605)
E/AndroidRuntime(31870):    at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(31870): Caused by: java.lang.NullPointerException
E/AndroidRuntime(31870):    at 
android.app.LoadedApk.initializeJavaContextClassLoader(LoadedApk.java:346)
E/AndroidRuntime(31870):    at 
android.app.LoadedApk.getClassLoader(LoadedApk.java:291)
E/AndroidRuntime(31870):    at 
android.app.LoadedApk.makeApplication(LoadedApk.java:458)
E/AndroidRuntime(31870):    ... 11 more
E/AndroidRuntime(31870): Error reporting crash
E/AndroidRuntime(31870): java.lang.IllegalArgumentException: Unknown package: 
org.damazio.notifier
E/AndroidRuntime(31870):    at android.os.Parcel.readException(Parcel.java:1326)
E/AndroidRuntime(31870):    at android.os.Parcel.readException(Parcel.java:1276)
E/AndroidRuntime(31870):    at 
android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.ja
va:2548)
E/AndroidRuntime(31870):    at 
com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeIni
t.java:87)
E/AndroidRuntime(31870):    at 
java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:854)
E/AndroidRuntime(31870):    at 
java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:851)
E/AndroidRuntime(31870):    at dalvik.system.NativeStart.main(Native Method)
E/WifiService( 2680): Multicaster binderDied
D/RemoteNotifier(  544): Connecting to Bluetooth device laugh 

What version of Android are you using? Gingerbread on samsung s 2.

```

Original issue reported on code.google.com by `uda...@gmail.com` on 6 Jul 2011 at 7:45

**Comment by GoogleCodeExporter** [comment]
```
I have meet the same problem 
```

Original comment by `wangzhen...@gmail.com` on 2 Sep 2013 at 7:19
