### ISSUE TITLE
No bluecov3_x64 in java.library.path

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CarlitoBriganteNT/android-notifier#448]
```
What steps will reproduce the problem?
1. Install MultiDroidNotifier-0.5.1-x86_64.exe on Win 7
2. Check Bluetooth

What is the expected output? What do you see instead?
Working bluetooth

What version of the product are you using? On what operating system?
 MultiDroidNotifier-0.5.1-x86_64.exe on Win 7

Please provide the log output if possible (from the alogcat app on android,
Show Log menu on the multiplatform client, or Console on native mac app):

2011-10-24 14:54:28,569 ERROR [ApplicationImpl] - Error starting [bluetooth] 
receiver
javax.bluetooth.BluetoothStateException: BlueCove library bluecove not 
available;
resource not found bluecove_x64.dll
load [bluecove_x64] no bluecove_x64 in java.library.path
    at com.intel.bluetooth.BlueCoveImpl.loadNativeLibraries(BlueCoveImpl.java:396)
    at com.intel.bluetooth.BlueCoveImpl.setBluetoothStack(BlueCoveImpl.java:963)
    at com.intel.bluetooth.BlueCoveImpl.detectStack(BlueCoveImpl.java:502)
    at com.intel.bluetooth.BlueCoveImpl.access$500(BlueCoveImpl.java:69)
    at com.intel.bluetooth.BlueCoveImpl$1.run(BlueCoveImpl.java:1044)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.intel.bluetooth.BlueCoveImpl.detectStackPrivileged(BlueCoveImpl.java:1042)
    at com.intel.bluetooth.BlueCoveImpl.getBluetoothStack(BlueCoveImpl.java:1035)
    at javax.bluetooth.LocalDevice.getLocalDeviceInstance(LocalDevice.java:75)
    at javax.bluetooth.LocalDevice.getLocalDevice(LocalDevice.java:95)
    at com.notifier.desktop.notification.bluetooth.BluetoothNotificationReceiver.doStart(BluetoothNotificationReceiver.java:54)
    at com.notifier.desktop.app.AbstractLifecycle.start(AbstractLifecycle.java:36)
    at com.notifier.desktop.app.ApplicationImpl.startLifecycle(ApplicationImpl.java:256)
    at com.notifier.desktop.app.ApplicationImpl.adjustLifecycle(ApplicationImpl.java:310)
    at com.notifier.desktop.app.ApplicationImpl.adjustBluetoothReceiver(ApplicationImpl.java:143)
    at com.notifier.desktop.view.PreferencesDialog$7$1.run(PreferencesDialog.java:320)
    at java.lang.Thread.run(Unknown Source)
```

Original issue reported on code.google.com by `mensoif...@gmail.com` on 24 Oct 2011 at 12:59

**Comment by GoogleCodeExporter** [comment]
```
Same for me
```

Original comment by `mickael....@gmail.com` on 17 Jun 2014 at 12:21
