### ISSUE TITLE
Desktop receives error when sending test notification by bluetooth

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CarlitoBriganteNT/android-notifier#449]
```
Desktop version: 0.5.1 (32-bit) on Win7
Remove Notifier version: 0.2.8 on Andoid 2.3.3 (HTC Desire S)

Battery, call and sms notifications works, but I get an error message in Win7 
when sending test notification from the phone:
"An error ocurred receiving bluetooth notification."

Log file:
2011-10-28 12:42:14,402 DEBUG [bluetooth] - connection accepted
2011-10-28 12:42:14,402 DEBUG [bluetooth] - socket[1152] getpeeraddress
2011-10-28 12:42:14,402 DEBUG [bluetooth] - connection open, open now 1
2011-10-28 12:42:14,403 DEBUG [bluetooth] - socket[1152] recv 
(byte[],int,int=4096)
2011-10-28 12:42:14,413 DEBUG [bluetooth] - Connection closed
2011-10-28 12:42:14,414 ERROR [BluetoothNotificationReceiver] - Error handling 
bluetooth notification
com.notifier.desktop.exception.ParseException: 
com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol 
message, the input ended unexpectedly in the middle of a field.  This could 
mean either than the input has been truncated or that an embedded message 
misreported its own length.
    at com.notifier.desktop.parsing.MultiNotificationParser.parse(MultiNotificationParser.java:53)
    at com.notifier.desktop.parsing.MultiNotificationParser.parse(MultiNotificationParser.java:27)
    at com.notifier.desktop.notification.bluetooth.BluetoothNotificationReceiver$1.run(BluetoothNotificationReceiver.java:87)
    at java.lang.Thread.run(Unknown Source)
Caused by: com.google.protobuf.InvalidProtocolBufferException: While parsing a 
protocol message, the input ended unexpectedly in the middle of a field.  This 
could mean either than the input has been truncated or that an embedded message 
misreported its own length.
    at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:49)
    at com.google.protobuf.CodedInputStream.refillBuffer(CodedInputStream.java:691)
    at com.google.protobuf.CodedInputStream.readRawByte(CodedInputStream.java:714)
    at com.google.protobuf.CodedInputStream.readRawVarint32(CodedInputStream.java:318)
    at com.notifier.desktop.parsing.MultiNotificationParser.parse(MultiNotificationParser.java:42)
    ... 3 more
2011-10-28 12:42:14,415 DEBUG [bluetooth] - closing RFCOMM Connection 1152
2011-10-28 12:42:14,415 DEBUG [bluetooth] - connection closed, open now 0
2011-10-28 12:42:14,416 DEBUG [bluetooth] - socket[1152] close
2011-10-28 12:42:14,416 DEBUG [bluetooth] - socket[1120] accept


```

Original issue reported on code.google.com by `jorn.dal...@gmail.com` on 28 Oct 2011 at 10:55

**Comment by GoogleCodeExporter** [comment]
```
I have this exact issue on Ubuntu 11.10 with a LG Thrill/Optimus 3D, although I 
dont think regular notifications work :P
```

Original comment by `brendan....@gmail.com` on 18 Jan 2012 at 5:31

**Comment by GoogleCodeExporter** [comment]
```
I have confirmed that for me notifications work on windows 7 but not on ubuntu 
11.10. Both are using 0.5.1, exe and deb. Will try with distro independent 
package

```

Original comment by `brendan....@gmail.com` on 19 Jan 2012 at 7:04

**Comment by GoogleCodeExporter** [comment]
```
Clarification: bluetooth notifications on Ubuntu give the error, wifi 
notifications on Windows do not. Will try wifi on ubuntu and bluetooth on 
windows.
```

Original comment by `brendan....@gmail.com` on 2 Feb 2012 at 6:44

**Comment by GoogleCodeExporter** [comment]
```
Can across something interesting. Normally my phone is listed in ubuntu as not 
connected until I try to send/receive files. I was able to get some test 
notifications through by spamming test notifications and then clicking "Browse 
files" in the ubuntu bluetooth settings window. This opens a connection to the 
phone allowing the test notifications through for a shot period of time. When I 
normally test notifications the connection does open however for some reason, 
sometimes when spamming I can get one through. 
```

Original comment by `brendan....@gmail.com` on 2 Feb 2012 at 7:19
