### ISSUE TITLE
Seems can`t work on ubuntu 12.04.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CarlitoBriganteNT/android-notifier#487]
```
IMPORTANT: PLEASE search the existing issues (including closed ones) for
something similar before filing a new one.

DO NOT, I repeat, DO NOT file more duplicates of issue 3 (bluetooth
notifications not working).

What steps will reproduce the problem?
i`ve just installed android-notifier-desktop on ubuntu 12.04, but i can`t start 
it.
It seems can`t work on ubuntu 12.04, is it my fault or the problem of the 
package?

What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?
ndroid-notifier-desktop_0.5.1-0_amd64.deb
ubuntu 12.04

Please provide the log output if possible (from the alogcat app on android,
Show Log menu on the multiplatform client, or Console on native mac app):


Please provide any additional information below.
```

Original issue reported on code.google.com by `eric6477...@gmail.com` on 3 Jun 2012 at 5:03

**Comment by GoogleCodeExporter** [comment]
```
I've same problem with i386 deb package!
```

Original comment by `kunalgau...@gmail.com` on 2 Jul 2012 at 1:47

**Comment by GoogleCodeExporter** [comment]
```
works perfect for me in 12.04 x64

java -version
java version "1.7.0_05"
Java(TM) SE Runtime Environment (build 1.7.0_05-b05)
Java HotSpot(TM) 64-Bit Server VM (build 23.1-b03, mixed mode)
```

Original comment by `bazili...@gmail.com` on 14 Aug 2012 at 7:47

**Comment by GoogleCodeExporter** [comment]
```
I get no visual notification, but I can hear a chime. I installed from 
android-notifier-desktop_0.5.1-0_amd64.deb and:
$ java -version
java version "1.7.0_09"
Java(TM) SE Runtime Environment (build 1.7.0_09-b05)
Java HotSpot(TM) 64-Bit Server VM (build 23.5-b02, mixed mode)
```

Original comment by `troll1...@gmail.com` on 5 Nov 2012 at 6:16

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Output when android-notifier-desktop.jar is run in the terminal:

2013-12-14 17:17:20,090 INFO [ApplicationImpl] - Starting SWT
2013-12-14 17:17:20,461 INFO [ApplicationImpl] - Showing tray icon
2013-12-14 17:17:20,640 DEBUG [ServiceServerImpl] - Starting service server on 
port [10700]
2013-12-14 17:17:20,656 DEBUG [InetAddresses] - Looking for local address
2013-12-14 17:17:20,687 DEBUG [InetAddresses] - Local address found
2013-12-14 17:17:20,690 INFO [ApplicationImpl] - Starting [System default] 
broadcaster
2013-12-14 17:17:20,691 INFO [ApplicationImpl] - Starting [TCP] receiver
2013-12-14 17:17:20,885 INFO [ApplicationImpl] - Starting [UDP] receiver
2013-12-14 17:17:20,924 INFO [ApplicationImpl] - Removing from startup
2013-12-14 17:17:20,929 ERROR [ApplicationImpl] - Error adjusting startup
java.io.IOException: Could not find autostart directory
    at com.notifier.desktop.app.OperatingSystems.getLinuxStartupDir(OperatingSystems.java:250)
    at com.notifier.desktop.app.OperatingSystems.removeFromLinuxStartup(OperatingSystems.java:239)
    at com.notifier.desktop.app.OperatingSystems.removeFromStartup(OperatingSystems.java:76)
    at com.notifier.desktop.app.ApplicationImpl.adjustStartup(ApplicationImpl.java:295)
    at com.notifier.desktop.app.ApplicationImpl.adjustStartAtLogin(ApplicationImpl.java:124)
    at com.notifier.desktop.app.ApplicationImpl.start(ApplicationImpl.java:104)
    at com.notifier.desktop.Main.main(Main.java:106)

```

Original comment by `madskate...@gmail.com` on 14 Dec 2013 at 4:19
