### ISSUE TITLE
an error occurred when receiving wifi notification: null

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CarlitoBriganteNT/android-notifier#522]
```
IMPORTANT: PLEASE search the existing issues (including closed ones) for
something similar before filing a new one.

DO NOT, I repeat, DO NOT file more duplicates of issue 3 (bluetooth
notifications not working).

What steps will reproduce the problem?
1.Receive any notifications
2.
3.

What is the expected output? What do you see instead?
I receive the notifications, but get "an error occurred when receiving wifi 
notification: null" as well.

What version of the product are you using? On what operating system?
0.2.8 Droid, Win7 x64 Pro, MultiDroidNotifier-0.5.1-x86 (using x86 version 
because not using Java x64 on Win7)

Please provide the log output if possible (from the alogcat app on android:
see attachment ("Log_2013-02-21_21-45-14.txt" 3.9mb)

Show Log menu on the multiplatform client, or Console on native mac app):
2013-02-21 19:56:10,744 INFO [ApplicationImpl] - Starting SWT
2013-02-21 19:56:10,794 ERROR [ApplicationImpl] - Error starting SWT
java.lang.UnsatisfiedLinkError: Cannot load 64-bit SWT libraries on 32-bit JVM
    at org.eclipse.swt.internal.Library.loadLibrary(Unknown Source)
    at org.eclipse.swt.internal.Library.loadLibrary(Unknown Source)
    at org.eclipse.swt.internal.C.<clinit>(Unknown Source)
    at org.eclipse.swt.widgets.Display.<clinit>(Unknown Source)
    at com.notifier.desktop.app.SwtManagerImpl.start(SwtManagerImpl.java:44)
    at com.notifier.desktop.app.ApplicationImpl.start(ApplicationImpl.java:69)
    at com.notifier.desktop.Main.main(Main.java:106)
2013-02-21 19:57:31,164 INFO [ApplicationImpl] - Starting SWT
2013-02-21 19:57:31,294 INFO [ApplicationImpl] - Showing tray icon
2013-02-21 19:57:31,384 DEBUG [ServiceServerImpl] - Starting service server on 
port [10700]
2013-02-21 19:57:31,424 DEBUG [InetAddresses] - Looking for local address
2013-02-21 19:57:31,434 INFO [ApplicationImpl] - Starting [System default] 
broadcaster
2013-02-21 19:57:31,444 INFO [ApplicationImpl] - Starting [TCP] receiver
2013-02-21 19:57:31,674 INFO [ApplicationImpl] - Starting [UDP] receiver
2013-02-21 19:57:31,724 INFO [ApplicationImpl] - Removing from startup
2013-02-21 19:57:31,774 DEBUG [InetAddresses] - Local address found
2013-02-21 19:58:19,204 INFO [NotificationManagerImpl] - Waiting for test 
notification to pair device
2013-02-21 19:58:22,444 INFO [NotificationManagerImpl] - Pairing stopped
2013-02-21 19:58:22,444 INFO [NotificationManagerImpl] - Pairing stopped
2013-02-21 20:00:33,634 INFO [NotificationManagerImpl] - Notification received: 
notificationId=1341463720276808, type=Ping
2013-02-21 20:00:49,904 INFO [ApplicationImpl] - Adding to startup
2013-02-21 20:02:18,744 INFO [NotificationManagerImpl] - Notification received: 
notificationId=1341463819059920, type=Ping
2013-02-21 20:02:32,929 INFO [NotificationManagerImpl] - Notification received: 
notificationId=1341463832504310, type=Ping
2013-02-21 20:03:13,972 INFO [NotificationManagerImpl] - Notification received: 
notificationId=1341463871363306, type=Ping
2013-02-21 20:03:36,181 INFO [NotificationManagerImpl] - Notification received: 
notificationId=1341463893048271, type=Ping
2013-02-21 20:03:44,088 ERROR [NotificationChannelHandler] - Error handling 
network notification
org.jboss.netty.handler.timeout.ReadTimeoutException
    at org.jboss.netty.handler.timeout.ReadTimeoutHandler.<clinit>(ReadTimeoutHandler.java:84)
    at com.notifier.desktop.notification.wifi.NotificationPipelineFactory.getPipeline(NotificationPipelineFactory.java:60)
    at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink$Boss.registerAcceptedChannel(NioServerSocketPipelineSink.java:276)
    at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink$Boss.run(NioServerSocketPipelineSink.java:247)
    at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
2013-02-21 20:07:57,103 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585740911102615, type=Battery
2013-02-21 20:32:38,999 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585785073702119, type=Battery
2013-02-21 20:32:58,048 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585787158049091, type=Battery
2013-02-21 20:33:05,517 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585376881923449, type=SMS
2013-02-21 20:33:09,099 ERROR [NotificationChannelHandler] - Error handling 
network notification
org.jboss.netty.handler.timeout.ReadTimeoutException
    at org.jboss.netty.handler.timeout.ReadTimeoutHandler.<clinit>(ReadTimeoutHandler.java:84)
    at com.notifier.desktop.notification.wifi.NotificationPipelineFactory.getPipeline(NotificationPipelineFactory.java:60)
    at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink$Boss.registerAcceptedChannel(NioServerSocketPipelineSink.java:276)
    at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink$Boss.run(NioServerSocketPipelineSink.java:247)
    at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
2013-02-21 20:33:27,551 INFO [NotificationManagerImpl] - Waiting for test 
notification to pair device
2013-02-21 20:33:31,689 INFO [NotificationManagerImpl] - Pairing stopped
2013-02-21 20:33:31,690 INFO [NotificationManagerImpl] - Pairing stopped
2013-02-21 20:38:02,166 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585796232150975, type=Battery
2013-02-21 20:43:47,657 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585806509122764, type=Battery
2013-02-21 20:48:07,852 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585814254903540, type=Battery
2013-02-21 20:48:18,707 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585403988006762, type=SMS
2013-02-21 20:48:37,968 ERROR [NotificationChannelHandler] - Error handling 
network notification
org.jboss.netty.handler.timeout.ReadTimeoutException
    at org.jboss.netty.handler.timeout.ReadTimeoutHandler.<clinit>(ReadTimeoutHandler.java:84)
    at com.notifier.desktop.notification.wifi.NotificationPipelineFactory.getPipeline(NotificationPipelineFactory.java:60)
    at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink$Boss.registerAcceptedChannel(NioServerSocketPipelineSink.java:276)
    at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink$Boss.run(NioServerSocketPipelineSink.java:247)
    at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
2013-02-21 20:49:25,978 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585407504115613, type=SMS
2013-02-21 20:49:56,078 ERROR [NotificationChannelHandler] - Error handling 
network notification
org.jboss.netty.handler.timeout.ReadTimeoutException
    at org.jboss.netty.handler.timeout.ReadTimeoutHandler.<clinit>(ReadTimeoutHandler.java:84)
    at com.notifier.desktop.notification.wifi.NotificationPipelineFactory.getPipeline(NotificationPipelineFactory.java:60)
    at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink$Boss.registerAcceptedChannel(NioServerSocketPipelineSink.java:276)
    at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink$Boss.run(NioServerSocketPipelineSink.java:247)
    at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
2013-02-21 20:49:58,025 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585406218178692, type=SMS
2013-02-21 20:50:16,148 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585406370427497, type=SMS
2013-02-21 20:50:31,103 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585817008823629, type=Battery
2013-02-21 20:51:21,168 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585818500101507, type=Battery
2013-02-21 20:54:01,937 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585412770149959, type=SMS
2013-02-21 20:54:12,075 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585412196872578, type=SMS
2013-02-21 20:55:14,036 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585418130512102, type=SMS
2013-02-21 20:55:22,221 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585416870354768, type=SMS
2013-02-21 20:55:31,231 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585415838901219, type=SMS
2013-02-21 20:56:01,331 ERROR [NotificationChannelHandler] - Error handling 
network notification
org.jboss.netty.handler.timeout.ReadTimeoutException
    at org.jboss.netty.handler.timeout.ReadTimeoutHandler.<clinit>(ReadTimeoutHandler.java:84)
    at com.notifier.desktop.notification.wifi.NotificationPipelineFactory.getPipeline(NotificationPipelineFactory.java:60)
    at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink$Boss.registerAcceptedChannel(NioServerSocketPipelineSink.java:276)
    at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink$Boss.run(NioServerSocketPipelineSink.java:247)
    at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
2013-02-21 20:57:00,726 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585420743751595, type=SMS
2013-02-21 21:05:28,117 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585435218164974, type=SMS
2013-02-21 21:06:04,760 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585434033371379, type=SMS
2013-02-21 21:09:27,619 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585440428823732, type=SMS
2013-02-21 21:09:41,948 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585440333981332, type=SMS
2013-02-21 21:10:12,056 ERROR [NotificationChannelHandler] - Error handling 
network notification
org.jboss.netty.handler.timeout.ReadTimeoutException
    at org.jboss.netty.handler.timeout.ReadTimeoutHandler.<clinit>(ReadTimeoutHandler.java:84)
    at com.notifier.desktop.notification.wifi.NotificationPipelineFactory.getPipeline(NotificationPipelineFactory.java:60)
    at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink$Boss.registerAcceptedChannel(NioServerSocketPipelineSink.java:276)
    at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink$Boss.run(NioServerSocketPipelineSink.java:247)
    at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)


Please provide any additional information below:

I have this set to use wifi, Bluetooth turned off, enable wifi on phone when 
needed. If wifi turned on on my phone, no error.
PC is 1 GB LAN, LAN/WLAN router (ASUS RT-N56U), router set to DHCP but 
assigning static IPs to PC and 'droid using MAC address in the router. PC set 
to DHCP.

Battery notifications = no error
SMS = error (random - I don't always get the pop-up error)


```

Original issue reported on code.google.com by `k0pe...@gmail.com` on 22 Feb 2013 at 3:04

Attachments:
- [Log_2013-02-21_21-45-14.txt](https://storage.googleapis.com/google-code-attachments/android-notifier/issue-522/comment-0/Log_2013-02-21_21-45-14.txt)

**Comment by GoogleCodeExporter** [comment]
```
Apologies, here is the log from Win7 client to match time-frame of Logcat 
Extreme log attachment:

2013-02-21 19:56:10,744 INFO [ApplicationImpl] - Starting SWT
2013-02-21 19:56:10,794 ERROR [ApplicationImpl] - Error starting SWT
java.lang.UnsatisfiedLinkError: Cannot load 64-bit SWT libraries on 32-bit JVM
    at org.eclipse.swt.internal.Library.loadLibrary(Unknown Source)
    at org.eclipse.swt.internal.Library.loadLibrary(Unknown Source)
    at org.eclipse.swt.internal.C.<clinit>(Unknown Source)
    at org.eclipse.swt.widgets.Display.<clinit>(Unknown Source)
    at com.notifier.desktop.app.SwtManagerImpl.start(SwtManagerImpl.java:44)
    at com.notifier.desktop.app.ApplicationImpl.start(ApplicationImpl.java:69)
    at com.notifier.desktop.Main.main(Main.java:106)
2013-02-21 19:57:31,164 INFO [ApplicationImpl] - Starting SWT
2013-02-21 19:57:31,294 INFO [ApplicationImpl] - Showing tray icon
2013-02-21 19:57:31,384 DEBUG [ServiceServerImpl] - Starting service server on 
port [10700]
2013-02-21 19:57:31,424 DEBUG [InetAddresses] - Looking for local address
2013-02-21 19:57:31,434 INFO [ApplicationImpl] - Starting [System default] 
broadcaster
2013-02-21 19:57:31,444 INFO [ApplicationImpl] - Starting [TCP] receiver
2013-02-21 19:57:31,674 INFO [ApplicationImpl] - Starting [UDP] receiver
2013-02-21 19:57:31,724 INFO [ApplicationImpl] - Removing from startup
2013-02-21 19:57:31,774 DEBUG [InetAddresses] - Local address found
2013-02-21 19:58:19,204 INFO [NotificationManagerImpl] - Waiting for test 
notification to pair device
2013-02-21 19:58:22,444 INFO [NotificationManagerImpl] - Pairing stopped
2013-02-21 19:58:22,444 INFO [NotificationManagerImpl] - Pairing stopped
2013-02-21 20:00:33,634 INFO [NotificationManagerImpl] - Notification received: 
notificationId=1341463720276808, type=Ping
2013-02-21 20:00:49,904 INFO [ApplicationImpl] - Adding to startup
2013-02-21 20:02:18,744 INFO [NotificationManagerImpl] - Notification received: 
notificationId=1341463819059920, type=Ping
2013-02-21 20:02:32,929 INFO [NotificationManagerImpl] - Notification received: 
notificationId=1341463832504310, type=Ping
2013-02-21 20:03:13,972 INFO [NotificationManagerImpl] - Notification received: 
notificationId=1341463871363306, type=Ping
2013-02-21 20:03:36,181 INFO [NotificationManagerImpl] - Notification received: 
notificationId=1341463893048271, type=Ping
2013-02-21 20:03:44,088 ERROR [NotificationChannelHandler] - Error handling 
network notification
org.jboss.netty.handler.timeout.ReadTimeoutException
    at org.jboss.netty.handler.timeout.ReadTimeoutHandler.<clinit>(ReadTimeoutHandler.java:84)
    at com.notifier.desktop.notification.wifi.NotificationPipelineFactory.getPipeline(NotificationPipelineFactory.java:60)
    at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink$Boss.registerAcceptedChannel(NioServerSocketPipelineSink.java:276)
    at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink$Boss.run(NioServerSocketPipelineSink.java:247)
    at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
2013-02-21 20:07:57,103 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585740911102615, type=Battery
2013-02-21 20:32:38,999 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585785073702119, type=Battery
2013-02-21 20:32:58,048 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585787158049091, type=Battery
2013-02-21 20:33:05,517 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585376881923449, type=SMS
2013-02-21 20:33:09,099 ERROR [NotificationChannelHandler] - Error handling 
network notification
org.jboss.netty.handler.timeout.ReadTimeoutException
    at org.jboss.netty.handler.timeout.ReadTimeoutHandler.<clinit>(ReadTimeoutHandler.java:84)
    at com.notifier.desktop.notification.wifi.NotificationPipelineFactory.getPipeline(NotificationPipelineFactory.java:60)
    at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink$Boss.registerAcceptedChannel(NioServerSocketPipelineSink.java:276)
    at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink$Boss.run(NioServerSocketPipelineSink.java:247)
    at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
2013-02-21 20:33:27,551 INFO [NotificationManagerImpl] - Waiting for test 
notification to pair device
2013-02-21 20:33:31,689 INFO [NotificationManagerImpl] - Pairing stopped
2013-02-21 20:33:31,690 INFO [NotificationManagerImpl] - Pairing stopped
2013-02-21 20:38:02,166 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585796232150975, type=Battery
2013-02-21 20:43:47,657 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585806509122764, type=Battery
2013-02-21 20:48:07,852 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585814254903540, type=Battery
2013-02-21 20:48:18,707 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585403988006762, type=SMS
2013-02-21 20:48:37,968 ERROR [NotificationChannelHandler] - Error handling 
network notification
org.jboss.netty.handler.timeout.ReadTimeoutException
    at org.jboss.netty.handler.timeout.ReadTimeoutHandler.<clinit>(ReadTimeoutHandler.java:84)
    at com.notifier.desktop.notification.wifi.NotificationPipelineFactory.getPipeline(NotificationPipelineFactory.java:60)
    at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink$Boss.registerAcceptedChannel(NioServerSocketPipelineSink.java:276)
    at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink$Boss.run(NioServerSocketPipelineSink.java:247)
    at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
2013-02-21 20:49:25,978 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585407504115613, type=SMS
2013-02-21 20:49:56,078 ERROR [NotificationChannelHandler] - Error handling 
network notification
org.jboss.netty.handler.timeout.ReadTimeoutException
    at org.jboss.netty.handler.timeout.ReadTimeoutHandler.<clinit>(ReadTimeoutHandler.java:84)
    at com.notifier.desktop.notification.wifi.NotificationPipelineFactory.getPipeline(NotificationPipelineFactory.java:60)
    at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink$Boss.registerAcceptedChannel(NioServerSocketPipelineSink.java:276)
    at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink$Boss.run(NioServerSocketPipelineSink.java:247)
    at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
2013-02-21 20:49:58,025 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585406218178692, type=SMS
2013-02-21 20:50:16,148 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585406370427497, type=SMS
2013-02-21 20:50:31,103 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585817008823629, type=Battery
2013-02-21 20:51:21,168 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585818500101507, type=Battery
2013-02-21 20:54:01,937 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585412770149959, type=SMS
2013-02-21 20:54:12,075 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585412196872578, type=SMS
2013-02-21 20:55:14,036 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585418130512102, type=SMS
2013-02-21 20:55:22,221 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585416870354768, type=SMS
2013-02-21 20:55:31,231 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585415838901219, type=SMS
2013-02-21 20:56:01,331 ERROR [NotificationChannelHandler] - Error handling 
network notification
org.jboss.netty.handler.timeout.ReadTimeoutException
    at org.jboss.netty.handler.timeout.ReadTimeoutHandler.<clinit>(ReadTimeoutHandler.java:84)
    at com.notifier.desktop.notification.wifi.NotificationPipelineFactory.getPipeline(NotificationPipelineFactory.java:60)
    at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink$Boss.registerAcceptedChannel(NioServerSocketPipelineSink.java:276)
    at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink$Boss.run(NioServerSocketPipelineSink.java:247)
    at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
2013-02-21 20:57:00,726 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585420743751595, type=SMS
2013-02-21 21:05:28,117 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585435218164974, type=SMS
2013-02-21 21:06:04,760 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585434033371379, type=SMS
2013-02-21 21:09:27,619 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585440428823732, type=SMS
2013-02-21 21:09:41,948 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585440333981332, type=SMS
2013-02-21 21:10:12,056 ERROR [NotificationChannelHandler] - Error handling 
network notification
org.jboss.netty.handler.timeout.ReadTimeoutException
    at org.jboss.netty.handler.timeout.ReadTimeoutHandler.<clinit>(ReadTimeoutHandler.java:84)
    at com.notifier.desktop.notification.wifi.NotificationPipelineFactory.getPipeline(NotificationPipelineFactory.java:60)
    at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink$Boss.registerAcceptedChannel(NioServerSocketPipelineSink.java:276)
    at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink$Boss.run(NioServerSocketPipelineSink.java:247)
    at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
2013-02-21 21:22:12,727 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585464782572306, type=SMS
2013-02-21 21:22:16,823 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585873747598582, type=Battery
2013-02-21 21:22:32,132 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585466742984735, type=SMS
2013-02-21 21:27:25,729 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585472222824307, type=SMS
2013-02-21 21:30:49,509 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585481514432116, type=SMS
2013-02-21 21:33:44,423 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585894275176381, type=Battery
2013-02-21 21:37:06,501 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585508893210894, type=SMS
2013-02-21 21:40:15,246 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585496642107626, type=SMS
2013-02-21 21:42:11,390 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585910893866936, type=Battery
2013-02-21 21:44:04,646 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585502329238955, type=SMS
2013-02-21 21:44:22,202 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585501874301049, type=SMS
2013-02-21 21:44:34,756 ERROR [NotificationChannelHandler] - Error handling 
network notification
org.jboss.netty.handler.timeout.ReadTimeoutException
    at org.jboss.netty.handler.timeout.ReadTimeoutHandler.<clinit>(ReadTimeoutHandler.java:84)
    at com.notifier.desktop.notification.wifi.NotificationPipelineFactory.getPipeline(NotificationPipelineFactory.java:60)
    at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink$Boss.registerAcceptedChannel(NioServerSocketPipelineSink.java:276)
    at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink$Boss.run(NioServerSocketPipelineSink.java:247)
    at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
2013-02-21 21:44:36,080 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585913667091593, type=Battery
2013-02-21 21:44:49,101 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585503440388762, type=SMS
2013-02-21 21:45:06,190 ERROR [NotificationChannelHandler] - Error handling 
network notification
org.jboss.netty.handler.timeout.ReadTimeoutException
    at org.jboss.netty.handler.timeout.ReadTimeoutHandler.<clinit>(ReadTimeoutHandler.java:84)
    at com.notifier.desktop.notification.wifi.NotificationPipelineFactory.getPipeline(NotificationPipelineFactory.java:60)
    at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink$Boss.registerAcceptedChannel(NioServerSocketPipelineSink.java:276)
    at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink$Boss.run(NioServerSocketPipelineSink.java:247)
    at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
2013-02-21 21:50:19,420 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585514414435714, type=SMS
2013-02-21 21:50:57,623 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585515088076967, type=SMS
2013-02-21 21:59:03,391 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585939587434724, type=Battery
2013-02-21 22:00:36,916 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585535107408656, type=SMS
2013-02-21 22:06:47,743 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585544929894085, type=SMS
2013-02-21 22:07:08,843 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585545818520485, type=SMS
2013-02-21 22:07:41,210 INFO [NotificationManagerImpl] - Notification received: 
notificationId=41585545083708247, type=SMS

```

Original comment by `k0pe...@gmail.com` on 22 Feb 2013 at 3:12

**Comment by GoogleCodeExporter** [comment]
```
Update: Mar 1, 2013 - Uninstalled Java, installed latest v7 upd15 (build 
1.7.0_15-b03), running for a week and this is only happening when I set to turn 
on Wifi on the phone if not currently on. If Wifi is already turned on, no 
error.
I would like to reiterate that the app works just fine, but all the 
notifications (one popup box per error) start to add up and they hide behind 
the active window, so when you close that window you have many many boxes to 
close manually.
* I tried Java x64 as well, same issues.

Thanks for playin'!

```

Original comment by `k0pe...@gmail.com` on 1 Mar 2013 at 11:26
