### ISSUE TITLE
Bluetooth fails to work on client

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CarlitoBriganteNT/android-notifier#576]
```
I am running manjaro 0.8.10 and blueman-bluez5-git from the aur on my laptop 
and I can connect through bluetooth normally to my device (Samsung Galaxy S4 
Mini). But when I try to enable bluetooth on the desktop client I get this 
error in the log.

2014-08-22 14:59:11,171 INFO [ApplicationImpl] - Starting [bluetooth] receiver
2014-08-22 14:59:11,190 DEBUG [bluetooth] - Java 1.4+ detected: 1.7.0_65; 
OpenJDK 64-Bit Server VM; Oracle Corporation
2014-08-22 14:59:11,198 DEBUG [bluetooth] - Use stack ClassLoader
2014-08-22 14:59:11,199 DEBUG [bluetooth] - set dll dir /tmp/bluecove_zelec_0
2014-08-22 14:59:11,201 DEBUG [bluetooth] - Library loaded from 
/tmp/bluecove_zelec_0/libbluecove_x64.so
2014-08-22 14:59:11,201 DEBUG [bluetooth] - BluetoothStack selected bluez
2014-08-22 14:59:11,201 DEBUG [bluetooth] - nativeDebugCallback ON
2014-08-22 14:59:11,202 DEBUG [bluetooth] - localDeviceID 0
2014-08-22 14:59:11,289 DEBUG [bluetooth] - open using BlueCove 
javax.microedition.io.Connector
2014-08-22 14:59:11,289 DEBUG [bluetooth] - connecting 
btspp://localhost:7674047e6e474bf0831f209e3f9dd23f;name=AndroidNotifierService;a
uthenticate=true;encrypt=true
2014-08-22 14:59:11,296 DEBUG [bluetooth] - RFCOMM set authenticate
2014-08-22 14:59:11,298 DEBUG [bluetooth] - will throw exception 
javax/bluetooth/ServiceRegistrationException(Can not open SDP session. [2] No 
such file or directory)
2014-08-22 14:59:11,298 DEBUG [bluetooth] - RFCOMM close server handle 41
2014-08-22 14:59:11,300 ERROR [BluetoothNotificationReceiver] - Error setting 
up bluetooth
javax.bluetooth.ServiceRegistrationException: Can not open SDP session. [2] No 
such file or directory
    at com.intel.bluetooth.BluetoothStackBlueZ.openSDPSessionImpl(Native Method)
    at com.intel.bluetooth.BluetoothStackBlueZ.getSDPSession(BluetoothStackBlueZ.java:518)
    at com.intel.bluetooth.BluetoothStackBlueZ.registerSDPRecord(BluetoothStackBlueZ.java:543)
    at com.intel.bluetooth.BluetoothStackBlueZ.rfServerOpen(BluetoothStackBlueZ.java:607)
    at com.intel.bluetooth.BluetoothRFCommConnectionNotifier.<init>(BluetoothRFCommConnectionNotifier.java:42)
    at com.intel.bluetooth.MicroeditionConnector.openImpl(MicroeditionConnector.java:377)
    at com.intel.bluetooth.MicroeditionConnector.open(MicroeditionConnector.java:162)
    at javax.microedition.io.Connector.open(Connector.java:83)
    at com.notifier.desktop.notification.bluetooth.BluetoothNotificationReceiver$1.run(BluetoothNotificationReceiver.java:75)
    at java.lang.Thread.run(Thread.java:745)

Is there any explanation to why this doesn't work
```

Original issue reported on code.google.com by `Zelec...@gmail.com` on 22 Aug 2014 at 7:05

**Comment by GoogleCodeExporter** [comment]
```
Same here, also on manjaro.
```

Original comment by `Daniel.W...@gmail.com` on 25 Oct 2014 at 6:26

**Comment by GoogleCodeExporter** [comment]
```
Hi there,

I have the same problem. I still don't know if it will work out for you or not, 
since I did a lot of install/uninstall before finding this, but I hadn't any 
problem when I ran compatibility mode on bluetooth (sudo service bluetooth stop 
&& add '-C' or '--compat' to ExecStart line in 
/usr/lib/systemd/system/bluetooth.service && sudo service bluetooth start)
AND ran android-desktop-notifier with privileges (sudo 
/usr/share/android-notifier-desktop/run.sh).

I was able to pair over Bluetooth, but I had su theming, meaning that other bad 
stuff could certainly be done (?)

Anyhow, right now I'm thinking that it is a permissions problem, but I cannot 
find which permissions I should change...

On Fedora 21 64-bit (kernel 3.18.7), bluez 5.23, xfce 4.11 (nonamedotc copr), 
using bluedevil as bluetooth front-end

```

Original comment by `GAgbob...@gmail.com` on 19 Feb 2015 at 3:49
